/**
 * FURNOSTYLES — FURNITURE DEMO DATA
 * =================================
 * File: shared/demo-data/furniture-demo.js
 * Purpose: Demo furniture products for marketplace testing
 * 
 * This is TEST/DUMMY data for demonstration purposes only.
 * No real payments, no real users, no real transactions.
 */

window.FurnostylesFurnitureDemo = {
  products: [
    // SOFAS (15 items)
    {
      id: "furn-001",
      title: "Modern L-Shaped Sofa - Grey Fabric",
      category: "Sofas",
      price: 85000,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/bed-burgundy-velvet-headboard.jpg",
      description: "Premium L-shaped sofa with grey fabric upholstery. Perfect for modern living rooms.",
      vendor: "Nairobi Luxury Furnishings"
    },
    {
      id: "furn-002",
      title: "Leather 3-Seater Sofa - Brown",
      category: "Sofas",
      price: 120000,
      location: "Westlands",
      condition: "New",
      featured: true,
      image: "assets/images/bed-brown-panel-headboard.jpg",
      description: "Genuine leather 3-seater sofa in rich brown. Durable and elegant.",
      vendor: "Urban Living Kenya"
    },
    {
      id: "furn-003",
      title: "Scandinavian Fabric Sofa - Beige",
      category: "Sofas",
      price: 95000,
      location: "Karen",
      condition: "New",
      featured: false,
      image: "assets/images/bed-grey-geometric-headboard.jpg",
      description: "Minimalist Scandinavian design with beige fabric. Clean and contemporary.",
      vendor: "Elite Interiors"
    },
    {
      id: "furn-004",
      title: "Chesterfield Sofa - Velvet Blue",
      category: "Sofas",
      price: 150000,
      location: "Kilimani",
      condition: "New",
      featured: true,
      image: "assets/images/bed-grey-stripe-teal-bench.jpg",
      description: "Classic Chesterfield design in royal blue velvet. Luxury statement piece.",
      vendor: "Nairobi Luxury Furnishings"
    },
    {
      id: "furn-005",
      title: "Recliner Sofa - Black Leather",
      category: "Sofas",
      price: 135000,
      location: "Mombasa",
      condition: "New",
      featured: false,
      image: "assets/images/tv-unit-white-gold-handles.jpg",
      description: "Power recliner sofa with black leather. Ultimate comfort.",
      vendor: "Coastal Comfort"
    },
    {
      id: "furn-006",
      title: "Corner Sofa - Grey Modular",
      category: "Sofas",
      price: 180000,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/tv-unit-white-oak.jpg",
      description: "Modular corner sofa system. Configurable for any space.",
      vendor: "Modern Living"
    },
    {
      id: "furn-007",
      title: "2-Seater Love Seat - Cream",
      category: "Sofas",
      price: 65000,
      location: "Kisumu",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-grey-sectional-luxury.jpg",
      description: "Compact 2-seater in cream fabric. Perfect for smaller spaces.",
      vendor: "Lake Region Furnishings"
    },
    {
      id: "furn-008",
      title: "Sofa Bed - Grey",
      category: "Sofas",
      price: 75000,
      location: "Nakuru",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-gold-set-curtains.jpg",
      description: "Convertible sofa bed. Guest room solution.",
      vendor: "Rift Valley Furniture"
    },
    {
      id: "furn-009",
      title: "Sectional Sofa - Navy Blue",
      category: "Sofas",
      price: 165000,
      location: "Eldoret",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-grey-u-shaped-teal.jpg",
      description: "Large sectional sofa in navy blue. Family-friendly.",
      vendor: "Highland Home Decor"
    },
    {
      id: "furn-010",
      title: "Mid-Century Modern Sofa - Teal",
      category: "Sofas",
      price: 110000,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/sofa-cream-sectional-set.jpg",
      description: "Mid-century modern design with teal upholstery. Retro charm.",
      vendor: "Vintage Vibes"
    },
    {
      id: "furn-011",
      title: "Chaise Lounge - Gold Fabric",
      category: "Sofas",
      price: 95000,
      location: "Kiambu",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-living-room-patterned.jpg",
      description: "Elegant chaise lounge in gold fabric. Luxury accent piece.",
      vendor: "County Classics"
    },
    {
      id: "furn-012",
      title: "Sofa Set - 3+2+1 - Brown",
      category: "Sofas",
      price: 220000,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/table-coffee-hardwood-1.jpg",
      description: "Complete sofa set: 3-seater, 2-seater, and armchair. Living room solution.",
      vendor: "Nairobi Luxury Furnishings"
    },
    {
      id: "furn-013",
      title: "Velvet Sofa - Emerald Green",
      category: "Sofas",
      price: 145000,
      location: "Westlands",
      condition: "New",
      featured: false,
      image: "assets/images/table-coffee-hardwood-2.jpg",
      description: "Luxurious velvet sofa in emerald green. Bold statement.",
      vendor: "Urban Living Kenya"
    },
    {
      id: "furn-014",
      title: "Ottoman Sofa Set - Grey",
      category: "Sofas",
      price: 105000,
      location: "Karen",
      condition: "New",
      featured: false,
      image: "assets/images/2.jpg",
      description: "Sofa with matching ottoman. Versatile comfort.",
      vendor: "Elite Interiors"
    },
    {
      id: "furn-015",
      title: "Patio Sofa Set - Rattan",
      category: "Sofas",
      price: 125000,
      location: "Mombasa",
      condition: "New",
      featured: false,
      image: "assets/images/bedroom-staging-modern-1.jpg",
      description: "Outdoor rattan sofa set. Weather-resistant.",
      vendor: "Coastal Comfort"
    },

    // BEDS (15 items)
    {
      id: "furn-016",
      title: "King Size Bed - Upholstered Grey",
      category: "Beds",
      price: 145000,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/sofa-cream-bubble-wood-table.jpg",
      description: "King size upholstered bed in grey fabric with storage.",
      vendor: "Nairobi Luxury Furnishings"
    },
    {
      id: "furn-017",
      title: "Queen Size Platform Bed - Oak",
      category: "Beds",
      price: 95000,
      location: "Westlands",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-brown-l-shaped-ottoman.jpg",
      description: "Solid oak platform bed. Natural wood finish.",
      vendor: "Woodcraft Kenya"
    },
    {
      id: "furn-018",
      title: "Double Bed - Metal Frame",
      category: "Beds",
      price: 65000,
      location: "Kisumu",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-grey-l-shaped-teal.jpg",
      description: "Industrial metal frame double bed. Modern minimalist.",
      vendor: "Lake Region Furnishings"
    },
    {
      id: "furn-019",
      title: "Super King Bed - Leather Headboard",
      category: "Beds",
      price: 185000,
      location: "Karen",
      condition: "New",
      featured: true,
      image: "assets/images/sofa-teal-velvet-set.jpg",
      description: "Super king with leather headboard. Ultimate luxury.",
      vendor: "Elite Interiors"
    },
    {
      id: "furn-020",
      title: "Bunk Bed - Solid Wood",
      category: "Beds",
      price: 55000,
      location: "Nakuru",
      condition: "New",
      featured: false,
      image: "assets/images/living-room-modern-orange.jpg",
      description: "Solid wood bunk bed. Perfect for kids' rooms.",
      vendor: "Rift Valley Furniture"
    },
    {
      id: "furn-021",
      title: "Storage Bed - Queen Size",
      category: "Beds",
      price: 115000,
      location: "Eldoret",
      condition: "New",
      featured: false,
      image: "assets/images/living-room-beige-cozy.jpg",
      description: "Queen bed with under-bed storage drawers.",
      vendor: "Highland Home Decor"
    },
    {
      id: "furn-022",
      title: "Four Poster Bed - Mahogany",
      category: "Beds",
      price: 225000,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/property-kitchen-dining.jpg",
      description: "Classic four poster bed in mahogany. Timeless elegance.",
      vendor: "Heritage Furniture"
    },
    {
      id: "furn-023",
      title: "Divan Bed Set - Memory Foam",
      category: "Beds",
      price: 135000,
      location: "Mombasa",
      condition: "New",
      featured: false,
      image: "assets/images/property-living-furnished.jpg",
      description: "Divan base with memory foam mattress included.",
      vendor: "Coastal Comfort"
    },
    {
      id: "furn-024",
      title: "Single Bed - Student",
      category: "Beds",
      price: 35000,
      location: "Kiambu",
      condition: "New",
      featured: false,
      image: "assets/images/table-nesting-black-glass-1.jpg",
      description: "Compact single bed. Perfect for students.",
      vendor: "County Classics"
    },
    {
      id: "furn-025",
      title: "Canopy Bed - White",
      category: "Beds",
      price: 195000,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/table-nesting-black-glass-2.jpg",
      description: "Romantic white canopy bed. Dreamy elegance.",
      vendor: "Nairobi Luxury Furnishings"
    },
    {
      id: "furn-026",
      title: "Day Bed - Grey",
      category: "Beds",
      price: 75000,
      location: "Westlands",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-cream-set-marble.jpg",
      description: "Versatile day bed for living room or guest room.",
      vendor: "Urban Living Kenya"
    },
    {
      id: "furn-027",
      title: "Adjustable Bed - Electric",
      category: "Beds",
      price: 285000,
      location: "Karen",
      condition: "New",
      featured: true,
      image: "assets/images/property-luxury-villa.jpg",
      description: "Electric adjustable bed with remote. Health-focused.",
      vendor: "Elite Interiors"
    },
    {
      id: "furn-028",
      title: "Trundle Bed - Twin",
      category: "Beds",
      price: 65000,
      location: "Kisumu",
      condition: "New",
      featured: false,
      image: "assets/images/bed-dark-wood-ottomans.jpg",
      description: "Twin bed with pull-out trundle. Space-saving.",
      vendor: "Lake Region Furnishings"
    },
    {
      id: "furn-029",
      title: "Sleigh Bed - Cherry Wood",
      category: "Beds",
      price: 165000,
      location: "Nakuru",
      condition: "New",
      featured: false,
      image: "assets/images/bedroom-staging-modern-2.jpg",
      description: "Classic sleigh bed in cherry wood. Warm tones.",
      vendor: "Rift Valley Furniture"
    },
    {
      id: "furn-030",
      title: "Murphy Bed - Wall Mounted",
      category: "Beds",
      price: 195000,
      location: "Nairobi",
      condition: "New",
      featured: false,
      image: "assets/images/bed-dark-headboard-blue.jpg",
      description: "Space-saving wall-mounted Murphy bed. Studio solution.",
      vendor: "Space Savers Kenya"
    },

    // DINING TABLES (12 items)
    {
      id: "furn-031",
      title: "6-Seater Dining Table - Oak",
      category: "Dining Tables",
      price: 85000,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/bathroom-grey-modern.jpg",
      description: "Solid oak dining table for 6. Natural finish.",
      vendor: "Woodcraft Kenya"
    },
    {
      id: "furn-032",
      title: "4-Seater Round Table - Glass",
      category: "Dining Tables",
      price: 65000,
      location: "Westlands",
      condition: "New",
      featured: false,
      image: "assets/images/table-coffee-round-wood.jpg",
      description: "Tempered glass round table. Modern elegance.",
      vendor: "Urban Living Kenya"
    },
    {
      id: "furn-033",
      title: "8-Seater Extending Table - Walnut",
      category: "Dining Tables",
      price: 145000,
      location: "Karen",
      condition: "New",
      featured: true,
      image: "assets/images/bed-dark-wood-suite-1.jpg",
      description: "Extending walnut table. Seats 8-10 comfortably.",
      vendor: "Elite Interiors"
    },
    {
      id: "furn-034",
      title: "Marble Top Dining Table - 6 Seater",
      category: "Dining Tables",
      price: 185000,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/bed-burgundy-velvet-headboard.jpg",
      description: "Luxurious marble top table. Premium statement.",
      vendor: "Nairobi Luxury Furnishings"
    },
    {
      id: "furn-035",
      title: "Drop-Leaf Table - Pine",
      category: "Dining Tables",
      price: 45000,
      location: "Kisumu",
      condition: "New",
      featured: false,
      image: "assets/images/bed-brown-panel-headboard.jpg",
      description: "Space-saving drop-leaf table. Flexible seating.",
      vendor: "Lake Region Furnishings"
    },
    {
      id: "furn-036",
      title: "Industrial Dining Table - Metal & Wood",
      category: "Dining Tables",
      price: 95000,
      location: "Mombasa",
      condition: "New",
      featured: false,
      image: "assets/images/bed-grey-geometric-headboard.jpg",
      description: "Industrial style with metal base and wood top.",
      vendor: "Coastal Comfort"
    },
    {
      id: "furn-037",
      title: "Pedestal Dining Table - Mahogany",
      category: "Dining Tables",
      price: 115000,
      location: "Nakuru",
      condition: "New",
      featured: false,
      image: "assets/images/bed-grey-stripe-teal-bench.jpg",
      description: "Single pedestal mahogany table. Classic design.",
      vendor: "Rift Valley Furniture"
    },
    {
      id: "furn-038",
      title: "Counter Height Table - 6 Seater",
      category: "Dining Tables",
      price: 75000,
      location: "Eldoret",
      condition: "New",
      featured: false,
      image: "assets/images/tv-unit-white-gold-handles.jpg",
      description: "Counter height table. Modern casual dining.",
      vendor: "Highland Home Decor"
    },
    {
      id: "furn-039",
      title: "Trestle Table - Reclaimed Wood",
      category: "Dining Tables",
      price: 105000,
      location: "Nairobi",
      condition: "New",
      featured: false,
      image: "assets/images/tv-unit-white-oak.jpg",
      description: "Rustic reclaimed wood trestle table. Farmhouse charm.",
      vendor: "Vintage Vibes"
    },
    {
      id: "furn-040",
      title: "Butterfly Leaf Table - White",
      category: "Dining Tables",
      price: 55000,
      location: "Kiambu",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-grey-sectional-luxury.jpg",
      description: "White butterfly leaf table. Clean and versatile.",
      vendor: "County Classics"
    },
    {
      id: "furn-041",
      title: "Conference Table - 10 Seater",
      category: "Dining Tables",
      price: 285000,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/sofa-gold-set-curtains.jpg",
      description: "Large conference table. Professional setting.",
      vendor: "Office Solutions Kenya"
    },
    {
      id: "furn-042",
      title: "Bistro Table - 2 Seater",
      category: "Dining Tables",
      price: 35000,
      location: "Westlands",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-grey-u-shaped-teal.jpg",
      description: "Compact bistro table. Perfect for small spaces.",
      vendor: "Urban Living Kenya"
    },

    // OFFICE DESKS (10 items)
    {
      id: "furn-043",
      title: "Executive Desk - Mahogany",
      category: "Office Desks",
      price: 145000,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/sofa-cream-sectional-set.jpg",
      description: "Large executive desk in mahogany. Premium office.",
      vendor: "Office Solutions Kenya"
    },
    {
      id: "furn-044",
      title: "Standing Desk - Electric",
      category: "Office Desks",
      price: 85000,
      location: "Westlands",
      condition: "New",
      featured: true,
      image: "assets/images/sofa-living-room-patterned.jpg",
      description: "Height-adjustable electric standing desk. Ergonomic.",
      vendor: "Modern Office Solutions"
    },
    {
      id: "furn-045",
      title: "L-Shaped Desk - Oak",
      category: "Office Desks",
      price: 65000,
      location: "Karen",
      condition: "New",
      featured: false,
      image: "assets/images/table-coffee-hardwood-1.jpg",
      description: "L-shaped oak desk. Corner workspace solution.",
      vendor: "Elite Interiors"
    },
    {
      id: "furn-046",
      title: "Writing Desk - White",
      category: "Office Desks",
      price: 35000,
      location: "Kisumu",
      condition: "New",
      featured: false,
      image: "assets/images/table-coffee-hardwood-2.jpg",
      description: "Simple white writing desk. Clean and functional.",
      vendor: "Lake Region Furnishings"
    },
    {
      id: "furn-047",
      title: "Reception Desk - Modern",
      category: "Office Desks",
      price: 115000,
      location: "Nairobi",
      condition: "New",
      featured: false,
      image: "assets/images/2.jpg",
      description: "Modern reception desk. Professional first impression.",
      vendor: "Office Solutions Kenya"
    },
    {
      id: "furn-048",
      title: "Computer Desk - Glass Top",
      category: "Office Desks",
      price: 45000,
      location: "Mombasa",
      condition: "New",
      featured: false,
      image: "assets/images/bedroom-staging-modern-1.jpg",
      description: "Glass top computer desk. Tech-friendly workspace.",
      vendor: "Coastal Comfort"
    },
    {
      id: "furn-049",
      title: "Credenza Desk - Walnut",
      category: "Office Desks",
      price: 95000,
      location: "Nakuru",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-cream-bubble-wood-table.jpg",
      description: "Credenza style desk with storage. Organized workspace.",
      vendor: "Rift Valley Furniture"
    },
    {
      id: "furn-050",
      title: "Floating Desk - Wall Mounted",
      category: "Office Desks",
      price: 25000,
      location: "Eldoret",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-brown-l-shaped-ottoman.jpg",
      description: "Space-saving wall-mounted desk. Minimalist.",
      vendor: "Highland Home Decor"
    },
    {
      id: "furn-051",
      title: "Drafting Table - Adjustable",
      category: "Office Desks",
      price: 75000,
      location: "Nairobi",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-grey-l-shaped-teal.jpg",
      description: "Adjustable angle drafting table. Creative workspace.",
      vendor: "Office Solutions Kenya"
    },
    {
      id: "furn-052",
      title: "Partner Desk - Double",
      category: "Office Desks",
      price: 125000,
      location: "Westlands",
      condition: "New",
      featured: true,
      image: "assets/images/sofa-teal-velvet-set.jpg",
      description: "Double partner desk. Shared workspace solution.",
      vendor: "Modern Office Solutions"
    },

    // TV STANDS (8 items)
    {
      id: "furn-053",
      title: "Modern TV Stand - Walnut",
      category: "TV Stands",
      price: 45000,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/living-room-modern-orange.jpg",
      description: "Walnut TV stand with storage. Entertainment center.",
      vendor: "Nairobi Luxury Furnishings"
    },
    {
      id: "furn-054",
      title: "Floating TV Unit - White",
      category: "TV Stands",
      price: 35000,
      location: "Karen",
      condition: "New",
      featured: false,
      image: "assets/images/living-room-beige-cozy.jpg",
      description: "Wall-mounted floating TV unit. Modern sleek.",
      vendor: "Elite Interiors"
    },
    {
      id: "furn-055",
      title: "Corner TV Stand - Oak",
      category: "TV Stands",
      price: 40000,
      location: "Kisumu",
      condition: "New",
      featured: false,
      image: "assets/images/property-kitchen-dining.jpg",
      description: "Corner-saving TV stand in oak. Efficient design.",
      vendor: "Lake Region Furnishings"
    },
    {
      id: "furn-056",
      title: "Entertainment Console - Low",
      category: "TV Stands",
      price: 55000,
      location: "Westlands",
      condition: "New",
      featured: false,
      image: "assets/images/property-living-furnished.jpg",
      description: "Low profile entertainment console. Minimalist.",
      vendor: "Urban Living Kenya"
    },
    {
      id: "furn-057",
      title: "TV Cabinet with Doors - Grey",
      category: "TV Stands",
      price: 65000,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/table-nesting-black-glass-1.jpg",
      description: "TV cabinet with closing doors. Hidden storage.",
      vendor: "Nairobi Luxury Furnishings"
    },
    {
      id: "furn-058",
      title: "Glass TV Stand - Chrome",
      category: "TV Stands",
      price: 75000,
      location: "Mombasa",
      condition: "New",
      featured: false,
      image: "assets/images/table-nesting-black-glass-2.jpg",
      description: "Glass and chrome TV stand. Contemporary style.",
      vendor: "Coastal Comfort"
    },
    {
      id: "furn-059",
      title: "Rustic TV Stand - Reclaimed Wood",
      category: "TV Stands",
      price: 55000,
      location: "Nakuru",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-cream-set-marble.jpg",
      description: "Rustic reclaimed wood TV stand. Farmhouse style.",
      vendor: "Rift Valley Furniture"
    },
    {
      id: "furn-060",
      title: "Rotating TV Stand - 360°",
      category: "TV Stands",
      price: 85000,
      location: "Eldoret",
      condition: "New",
      featured: false,
      image: "assets/images/property-luxury-villa.jpg",
      description: "360° rotating TV stand. Flexible viewing.",
      vendor: "Highland Home Decor"
    },

    // WARROBES (10 items)
    {
      id: "furn-061",
      title: "3-Door Wardrobe - White",
      category: "Wardrobes",
      price: 85000,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/bed-dark-wood-ottomans.jpg",
      description: "3-door white wardrobe with mirrors. Spacious storage.",
      vendor: "Nairobi Luxury Furnishings"
    },
    {
      id: "furn-062",
      title: "Sliding Door Wardrobe - Oak",
      category: "Wardrobes",
      price: 115000,
      location: "Karen",
      condition: "New",
      featured: true,
      image: "assets/images/bedroom-staging-modern-2.jpg",
      description: "Sliding door wardrobe in oak. Space-saving design.",
      vendor: "Elite Interiors"
    },
    {
      id: "furn-063",
      title: "Walk-in Wardrobe System",
      category: "Wardrobes",
      price: 285000,
      location: "Westlands",
      condition: "New",
      featured: true,
      image: "assets/images/bed-dark-headboard-blue.jpg",
      description: "Complete walk-in wardrobe system. Luxury storage.",
      vendor: "Urban Living Kenya"
    },
    {
      id: "furn-064",
      title: "2-Door Wardrobe - Pine",
      category: "Wardrobes",
      price: 65000,
      location: "Kisumu",
      condition: "New",
      featured: false,
      image: "assets/images/bathroom-grey-modern.jpg",
      description: "Simple 2-door pine wardrobe. Classic storage.",
      vendor: "Lake Region Furnishings"
    },
    {
      id: "furn-065",
      title: "Corner Wardrobe - Grey",
      category: "Wardrobes",
      price: 95000,
      location: "Nairobi",
      condition: "New",
      featured: false,
      image: "assets/images/table-coffee-round-wood.jpg",
      description: "Corner wardrobe design. Efficient use of space.",
      vendor: "Space Savers Kenya"
    },
    {
      id: "furn-066",
      title: "Mirrored Wardrobe - 4 Door",
      category: "Wardrobes",
      price: 145000,
      location: "Mombasa",
      condition: "New",
      featured: false,
      image: "assets/images/bed-dark-wood-suite-1.jpg",
      description: "4-door wardrobe with full mirrors. Bright and spacious.",
      vendor: "Coastal Comfort"
    },
    {
      id: "furn-067",
      title: "Built-in Wardrobe - Custom",
      category: "Wardrobes",
      price: 195000,
      location: "Nakuru",
      condition: "New",
      featured: false,
      image: "assets/images/bed-burgundy-velvet-headboard.jpg",
      description: "Custom built-in wardrobe solution. Tailored fit.",
      vendor: "Rift Valley Furniture"
    },
    {
      id: "furn-068",
      title: "Kids Wardrobe - Colorful",
      category: "Wardrobes",
      price: 55000,
      location: "Eldoret",
      condition: "New",
      featured: false,
      image: "assets/images/bed-brown-panel-headboard.jpg",
      description: "Colorful kids wardrobe with fun design.",
      vendor: "Highland Home Decor"
    },
    {
      id: "furn-069",
      title: "Wardrobe with Drawers - Walnut",
      category: "Wardrobes",
      price: 125000,
      location: "Kiambu",
      condition: "New",
      featured: false,
      image: "assets/images/bed-grey-geometric-headboard.jpg",
      description: "Wardrobe with integrated drawers. Organized storage.",
      vendor: "County Classics"
    },
    {
      id: "furn-070",
      title: "Open Wardrobe - Industrial",
      category: "Wardrobes",
      price: 85000,
      location: "Nairobi",
      condition: "New",
      featured: false,
      image: "assets/images/bed-grey-stripe-teal-bench.jpg",
      description: "Open industrial style wardrobe. Modern display.",
      vendor: "Vintage Vibes"
    },

    // KITCHEN CABINETS (10 items)
    {
      id: "furn-071",
      title: "Modern Kitchen Cabinet Set - White",
      category: "Kitchen Cabinets",
      price: 285000,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/tv-unit-white-gold-handles.jpg",
      description: "Complete modern kitchen cabinet set in white.",
      vendor: "Nairobi Luxury Furnishings"
    },
    {
      id: "furn-072",
      title: "Shaker Style Cabinets - Grey",
      category: "Kitchen Cabinets",
      price: 245000,
      location: "Karen",
      condition: "New",
      featured: true,
      image: "assets/images/tv-unit-white-oak.jpg",
      description: "Shaker style grey cabinets. Classic modern.",
      vendor: "Elite Interiors"
    },
    {
      id: "furn-073",
      title: "Kitchen Island with Storage",
      category: "Kitchen Cabinets",
      price: 125000,
      location: "Westlands",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-grey-sectional-luxury.jpg",
      description: "Kitchen island with ample storage. Prep station.",
      vendor: "Urban Living Kenya"
    },
    {
      id: "furn-074",
      title: "Corner Cabinet - Lazy Susan",
      category: "Kitchen Cabinets",
      price: 65000,
      location: "Kisumu",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-gold-set-curtains.jpg",
      description: "Corner cabinet with lazy Susan. Smart storage.",
      vendor: "Lake Region Furnishings"
    },
    {
      id: "furn-075",
      title: "Upper Wall Cabinets - Oak",
      category: "Kitchen Cabinets",
      price: 145000,
      location: "Mombasa",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-grey-u-shaped-teal.jpg",
      description: "Set of oak wall cabinets. Upper storage.",
      vendor: "Coastal Comfort"
    },
    {
      id: "furn-076",
      title: "Base Cabinets - Walnut",
      category: "Kitchen Cabinets",
      price: 165000,
      location: "Nakuru",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-cream-sectional-set.jpg",
      description: "Set of walnut base cabinets. Foundation storage.",
      vendor: "Rift Valley Furniture"
    },
    {
      id: "furn-077",
      title: "Pantry Cabinet - Tall",
      category: "Kitchen Cabinets",
      price: 85000,
      location: "Eldoret",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-living-room-patterned.jpg",
      description: "Tall pantry cabinet. Food storage solution.",
      vendor: "Highland Home Decor"
    },
    {
      id: "furn-078",
      title: "Under-Sink Cabinet - Grey",
      category: "Kitchen Cabinets",
      price: 45000,
      location: "Kiambu",
      condition: "New",
      featured: false,
      image: "assets/images/table-coffee-hardwood-1.jpg",
      description: "Under-sink cabinet with door. Utility storage.",
      vendor: "County Classics"
    },
    {
      id: "furn-079",
      title: "Open Shelving Unit - Industrial",
      category: "Kitchen Cabinets",
      price: 55000,
      location: "Nairobi",
      condition: "New",
      featured: false,
      image: "assets/images/table-coffee-hardwood-2.jpg",
      description: "Industrial open shelving. Display storage.",
      vendor: "Vintage Vibes"
    },
    {
      id: "furn-080",
      title: "Appliance Garage Cabinet",
      category: "Kitchen Cabinets",
      price: 75000,
      location: "Westlands",
      condition: "New",
      featured: false,
      image: "assets/images/2.jpg",
      description: "Appliance garage cabinet. Hidden appliances.",
      vendor: "Urban Living Kenya"
    },

    // SHELVES (8 items)
    {
      id: "furn-081",
      title: "5-Tier Bookshelf - Oak",
      category: "Shelves",
      price: 35000,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/bedroom-staging-modern-1.jpg",
      description: "5-tier oak bookshelf. Classic storage.",
      vendor: "Woodcraft Kenya"
    },
    {
      id: "furn-082",
      title: "Floating Wall Shelves - Set of 3",
      category: "Shelves",
      price: 25000,
      location: "Karen",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-cream-bubble-wood-table.jpg",
      description: "Set of 3 floating shelves. Modern display.",
      vendor: "Elite Interiors"
    },
    {
      id: "furn-083",
      title: "Ladder Shelf - Industrial",
      category: "Shelves",
      price: 45000,
      location: "Westlands",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-brown-l-shaped-ottoman.jpg",
      description: "Industrial ladder shelf. Stylish storage.",
      vendor: "Urban Living Kenya"
    },
    {
      id: "furn-084",
      title: "Cube Storage Unit - 9 Cubes",
      category: "Shelves",
      price: 35000,
      location: "Kisumu",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-grey-l-shaped-teal.jpg",
      description: "9-cube storage unit. Versatile organizer.",
      vendor: "Lake Region Furnishings"
    },
    {
      id: "furn-085",
      title: "Corner Shelf - Revolving",
      category: "Shelves",
      price: 30000,
      location: "Mombasa",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-teal-velvet-set.jpg",
      description: "Revolving corner shelf. Space-saving.",
      vendor: "Coastal Comfort"
    },
    {
      id: "furn-086",
      title: "Glass Display Cabinet",
      category: "Shelves",
      price: 85000,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/living-room-modern-orange.jpg",
      description: "Glass display cabinet with lighting. Showcase.",
      vendor: "Nairobi Luxury Furnishings"
    },
    {
      id: "furn-087",
      title: "Modular Shelving System",
      category: "Shelves",
      price: 95000,
      location: "Nakuru",
      condition: "New",
      featured: false,
      image: "assets/images/living-room-beige-cozy.jpg",
      description: "Configurable modular shelving. Custom layout.",
      vendor: "Rift Valley Furniture"
    },
    {
      id: "furn-088",
      title: "Wall-Mounted Rack - Metal",
      category: "Shelves",
      price: 20000,
      location: "Eldoret",
      condition: "New",
      featured: false,
      image: "assets/images/property-kitchen-dining.jpg",
      description: "Metal wall-mounted rack. Industrial style.",
      vendor: "Highland Home Decor"
    },

    // COFFEE TABLES (7 items)
    {
      id: "furn-089",
      title: "Round Coffee Table - Marble",
      category: "Coffee Tables",
      price: 65000,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/property-living-furnished.jpg",
      description: "Round marble coffee table. Luxury centerpiece.",
      vendor: "Nairobi Luxury Furnishings"
    },
    {
      id: "furn-090",
      title: "Square Coffee Table - Oak",
      category: "Coffee Tables",
      price: 35000,
      location: "Karen",
      condition: "New",
      featured: false,
      image: "assets/images/table-nesting-black-glass-1.jpg",
      description: "Square oak coffee table. Natural warmth.",
      vendor: "Elite Interiors"
    },
    {
      id: "furn-091",
      title: "Glass Coffee Table - Chrome",
      category: "Coffee Tables",
      price: 45000,
      location: "Westlands",
      condition: "New",
      featured: false,
      image: "assets/images/table-nesting-black-glass-2.jpg",
      description: "Glass and chrome coffee table. Modern sleek.",
      vendor: "Urban Living Kenya"
    },
    {
      id: "furn-092",
      title: "Lift-Top Coffee Table - Storage",
      category: "Coffee Tables",
      price: 55000,
      location: "Kisumu",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-cream-set-marble.jpg",
      description: "Lift-top table with hidden storage. Functional.",
      vendor: "Lake Region Furnishings"
    },
    {
      id: "furn-093",
      title: "Nesting Coffee Tables - Set of 3",
      category: "Coffee Tables",
      price: 45000,
      location: "Mombasa",
      condition: "New",
      featured: false,
      image: "assets/images/property-luxury-villa.jpg",
      description: "Set of 3 nesting tables. Flexible arrangement.",
      vendor: "Coastal Comfort"
    },
    {
      id: "furn-094",
      title: "Wooden Crate Coffee Table",
      category: "Coffee Tables",
      price: 35000,
      location: "Nakuru",
      condition: "New",
      featured: false,
      image: "assets/images/bed-dark-wood-ottomans.jpg",
      description: "Rustic crate style coffee table. Farmhouse charm.",
      vendor: "Rift Valley Furniture"
    },
    {
      id: "furn-095",
      title: "Oval Coffee Table - Walnut",
      category: "Coffee Tables",
      price: 55000,
      location: "Eldoret",
      condition: "New",
      featured: false,
      image: "assets/images/bedroom-staging-modern-2.jpg",
      description: "Oval walnut coffee table. Elegant curves.",
      vendor: "Highland Home Decor"
    },

    // LUXURY FURNITURE (5 items)
    {
      id: "furn-096",
      title: "Italian Leather Sectional - White",
      category: "Luxury Furniture",
      price: 485000,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/bed-dark-headboard-blue.jpg",
      description: "Imported Italian leather sectional. Ultimate luxury.",
      vendor: "Nairobi Luxury Furnishings"
    },
    {
      id: "furn-097",
      title: "Designer Chandelier - Crystal",
      category: "Luxury Furniture",
      price: 285000,
      location: "Karen",
      condition: "New",
      featured: true,
      image: "assets/images/bathroom-grey-modern.jpg",
      description: "Crystal designer chandelier. Statement lighting.",
      vendor: "Elite Interiors"
    },
    {
      id: "furn-098",
      title: "Gold Accent Table - Marble Top",
      category: "Luxury Furniture",
      price: 145000,
      location: "Westlands",
      condition: "New",
      featured: false,
      image: "assets/images/table-coffee-round-wood.jpg",
      description: "Gold base with marble top. Luxury accent.",
      vendor: "Urban Living Kenya"
    },
    {
      id: "furn-099",
      title: "Velvet Armchair - Emerald",
      category: "Luxury Furniture",
      price: 125000,
      location: "Nairobi",
      condition: "New",
      featured: false,
      image: "assets/images/bed-dark-wood-suite-1.jpg",
      description: "Emerald velvet armchair. Luxury seating.",
      vendor: "Nairobi Luxury Furnishings"
    },
    {
      id: "furn-100",
      title: "Persian Rug - Handmade",
      category: "Luxury Furniture",
      price: 185000,
      location: "Mombasa",
      condition: "New",
      featured: false,
      image: "assets/images/bed-burgundy-velvet-headboard.jpg",
      description: "Handmade Persian rug. Artisan craftsmanship.",
      vendor: "Coastal Comfort"
    }
  ],

  // Categories for filtering
  categories: [
    "Sofas",
    "Beds",
    "Dining Tables",
    "Office Desks",
    "TV Stands",
    "Wardrobes",
    "Kitchen Cabinets",
    "Shelves",
    "Coffee Tables",
    "Luxury Furniture"
  ],

  // Locations for filtering
  locations: [
    "Nairobi",
    "Westlands",
    "Karen",
    "Kilimani",
    "Mombasa",
    "Kisumu",
    "Nakuru",
    "Eldoret",
    "Kiambu"
  ],

  // Price ranges for filtering
  priceRanges: [
    { min: 0, max: 50000, label: "Under KSh 50,000" },
    { min: 50000, max: 100000, label: "KSh 50,000 - KSh 100,000" },
    { min: 100000, max: 200000, label: "KSh 100,000 - KSh 200,000" },
    { min: 200000, max: 999999, label: "KSh 200,000+" }
  ]
};
