/**
 * FURNOSTYLES — MATERIALS & HARDWARE DEMO DATA
 * ==========================================
 * File: shared/demo-data/materials-demo.js
 * Purpose: Demo materials and hardware products for marketplace testing
 * 
 * This is TEST/DUMMY data for demonstration purposes only.
 * No real payments, no real users, no real transactions.
 */

window.FurnostylesMaterialsDemo = {
  products: [
    // PAINT (12 items)
    {
      id: "mat-001",
      title: "Interior Emulsion Paint - White 20L",
      category: "Paint",
      price: 8500,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/bed-burgundy-velvet-headboard.jpg",
      description: "Premium interior emulsion paint. High coverage, smooth finish.",
      vendor: "Metro Hardware Supplies"
    },
    {
      id: "mat-002",
      title: "Exterior Weatherproof Paint - Grey 20L",
      category: "Paint",
      price: 12000,
      location: "Westlands",
      condition: "New",
      featured: true,
      image: "assets/images/bed-brown-panel-headboard.jpg",
      description: "Weatherproof exterior paint. UV resistant, durable.",
      vendor: "Metro Hardware Supplies"
    },
    {
      id: "mat-003",
      title: "Oil-Based Enamel Paint - Gloss 5L",
      category: "Paint",
      price: 4500,
      location: "Karen",
      condition: "New",
      featured: false,
      image: "assets/images/bed-grey-geometric-headboard.jpg",
      description: "Gloss enamel for wood and metal. Hard-wearing finish.",
      vendor: "Elite Paints Kenya"
    },
    {
      id: "mat-004",
      title: "Matte Wall Paint - Beige 20L",
      category: "Paint",
      price: 9500,
      location: "Kisumu",
      condition: "New",
      featured: false,
      image: "assets/images/bed-grey-stripe-teal-bench.jpg",
      description: "Matte finish wall paint. Elegant and modern.",
      vendor: "Lake Region Hardware"
    },
    {
      id: "mat-005",
      title: "Roof Paint - Red 20L",
      category: "Paint",
      price: 11000,
      location: "Mombasa",
      condition: "New",
      featured: false,
      image: "assets/images/tv-unit-white-gold-handles.jpg",
      description: "Specialized roof paint. Heat reflective, long-lasting.",
      vendor: "Coastal Building Supplies"
    },
    {
      id: "mat-006",
      title: "Primer Sealer - Clear 10L",
      category: "Paint",
      price: 6500,
      location: "Nakuru",
      condition: "New",
      featured: false,
      image: "assets/images/tv-unit-white-oak.jpg",
      description: "Multi-surface primer sealer. Prepares surfaces for painting.",
      vendor: "Rift Valley Hardware"
    },
    {
      id: "mat-007",
      title: "Anti-Mold Paint - Bathroom 5L",
      category: "Paint",
      price: 5500,
      location: "Eldoret",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-grey-sectional-luxury.jpg",
      description: "Anti-mold bathroom paint. Moisture resistant.",
      vendor: "Highland Building Materials"
    },
    {
      id: "mat-008",
      title: "Textured Paint - Stone Effect 20L",
      category: "Paint",
      price: 14500,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/sofa-gold-set-curtains.jpg",
      description: "Textured stone effect paint. Decorative finish.",
      vendor: "Metro Hardware Supplies"
    },
    {
      id: "mat-009",
      title: "Chalkboard Paint - Black 5L",
      category: "Paint",
      price: 3500,
      location: "Kiambu",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-grey-u-shaped-teal.jpg",
      description: "Chalkboard paint. Create writable surfaces.",
      vendor: "County Hardware"
    },
    {
      id: "mat-010",
      title: "Metal Paint - Rust-Oleum 5L",
      category: "Paint",
      price: 6500,
      location: "Westlands",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-cream-sectional-set.jpg",
      description: "Rust-preventive metal paint. Industrial strength.",
      vendor: "Metro Hardware Supplies"
    },
    {
      id: "mat-011",
      title: "Floor Paint - Epoxy 20L",
      category: "Paint",
      price: 18500,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/sofa-living-room-patterned.jpg",
      description: "Epoxy floor paint. Heavy-duty, chemical resistant.",
      vendor: "Industrial Supplies Kenya"
    },
    {
      id: "mat-012",
      title: "Spray Paint - Assorted Colors",
      category: "Paint",
      price: 850,
      location: "Karen",
      condition: "New",
      featured: false,
      image: "assets/images/table-coffee-hardwood-1.jpg",
      description: "Aerosol spray paint. Quick touch-ups.",
      vendor: "Elite Paints Kenya"
    },

    // TILES (12 items)
    {
      id: "mat-013",
      title: "Ceramic Floor Tiles - 60x60cm Grey",
      category: "Tiles",
      price: 1200,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/table-coffee-hardwood-2.jpg",
      description: "Premium ceramic floor tiles. Durable and stylish.",
      vendor: "Tile Masters Kenya"
    },
    {
      id: "mat-014",
      title: "Porcelain Wall Tiles - 30x60cm White",
      category: "Tiles",
      price: 950,
      location: "Westlands",
      condition: "New",
      featured: false,
      image: "assets/images/2.jpg",
      description: "White porcelain wall tiles. Clean and bright.",
      vendor: "Tile Masters Kenya"
    },
    {
      id: "mat-015",
      title: "Marble Effect Tiles - 60x60cm Beige",
      category: "Tiles",
      price: 1800,
      location: "Karen",
      condition: "New",
      featured: true,
      image: "assets/images/bedroom-staging-modern-1.jpg",
      description: "Marble effect porcelain tiles. Luxury look.",
      vendor: "Elite Tiles"
    },
    {
      id: "mat-016",
      title: "Bathroom Mosaic Tiles - 10x10cm Blue",
      category: "Tiles",
      price: 1500,
      location: "Kisumu",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-cream-bubble-wood-table.jpg",
      description: "Blue mosaic bathroom tiles. Decorative accents.",
      vendor: "Lake Region Hardware"
    },
    {
      id: "mat-017",
      title: "Kitchen Backsplash Tiles - 30x30cm",
      category: "Tiles",
      price: 1100,
      location: "Mombasa",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-brown-l-shaped-ottoman.jpg",
      description: "Kitchen backsplash tiles. Easy to clean.",
      vendor: "Coastal Building Supplies"
    },
    {
      id: "mat-018",
      title: "Outdoor Paver Tiles - 40x40cm Grey",
      category: "Tiles",
      price: 850,
      location: "Nakuru",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-grey-l-shaped-teal.jpg",
      description: "Heavy-duty outdoor pavers. Weather resistant.",
      vendor: "Rift Valley Hardware"
    },
    {
      id: "mat-019",
      title: "Wood Look Tiles - 120x20cm Oak",
      category: "Tiles",
      price: 2200,
      location: "Eldoret",
      condition: "New",
      featured: true,
      image: "assets/images/sofa-teal-velvet-set.jpg",
      description: "Wood-look porcelain tiles. Warm natural look.",
      vendor: "Highland Building Materials"
    },
    {
      id: "mat-020",
      title: "Terracotta Floor Tiles - 30x30cm Red",
      category: "Tiles",
      price: 750,
      location: "Kiambu",
      condition: "New",
      featured: false,
      image: "assets/images/living-room-modern-orange.jpg",
      description: "Traditional terracotta tiles. Rustic charm.",
      vendor: "County Hardware"
    },
    {
      id: "mat-021",
      title: "Glossy Wall Tiles - 25x40cm Cream",
      category: "Tiles",
      price: 850,
      location: "Nairobi",
      condition: "New",
      featured: false,
      image: "assets/images/living-room-beige-cozy.jpg",
      description: "Glossy cream wall tiles. Reflective finish.",
      vendor: "Tile Masters Kenya"
    },
    {
      id: "mat-022",
      title: "Anti-Slip Floor Tiles - 40x40cm",
      category: "Tiles",
      price: 1350,
      location: "Westlands",
      condition: "New",
      featured: false,
      image: "assets/images/property-kitchen-dining.jpg",
      description: "Anti-slip safety tiles. For wet areas.",
      vendor: "Tile Masters Kenya"
    },
    {
      id: "mat-023",
      title: "Granite Tiles - 60x60cm Black",
      category: "Tiles",
      price: 2500,
      location: "Karen",
      condition: "New",
      featured: true,
      image: "assets/images/property-living-furnished.jpg",
      description: "Premium granite tiles. Luxury flooring.",
      vendor: "Elite Tiles"
    },
    {
      id: "mat-024",
      title: "Subway Tiles - 10x20cm White",
      category: "Tiles",
      price: 650,
      location: "Mombasa",
      condition: "New",
      featured: false,
      image: "assets/images/table-nesting-black-glass-1.jpg",
      description: "Classic subway tiles. Timeless design.",
      vendor: "Coastal Building Supplies"
    },

    // PLUMBING FITTINGS (12 items)
    {
      id: "mat-025",
      title: "Kitchen Sink Mixer Tap - Chrome",
      category: "Plumbing Fittings",
      price: 4500,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/table-nesting-black-glass-2.jpg",
      description: "Single lever kitchen mixer. Modern design.",
      vendor: "PlumbPro Kenya"
    },
    {
      id: "mat-026",
      title: "Bathroom Basin Mixer - Chrome",
      category: "Plumbing Fittings",
      price: 3500,
      location: "Westlands",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-cream-set-marble.jpg",
      description: "Basin mixer tap. Elegant chrome finish.",
      vendor: "PlumbPro Kenya"
    },
    {
      id: "mat-027",
      title: "Shower Set - Rainfall Head",
      category: "Plumbing Fittings",
      price: 8500,
      location: "Karen",
      condition: "New",
      featured: true,
      image: "assets/images/property-luxury-villa.jpg",
      description: "Luxury rainfall shower set. Spa experience.",
      vendor: "Elite Bathrooms"
    },
    {
      id: "mat-028",
      title: "Toilet Flush Valve - Dual",
      category: "Plumbing Fittings",
      price: 1500,
      location: "Kisumu",
      condition: "New",
      featured: false,
      image: "assets/images/bed-dark-wood-ottomans.jpg",
      description: "Dual flush toilet valve. Water efficient.",
      vendor: "Lake Region Hardware"
    },
    {
      id: "mat-029",
      title: "P-Trap Pipe - 50mm PVC",
      category: "Plumbing Fittings",
      price: 450,
      location: "Mombasa",
      condition: "New",
      featured: false,
      image: "assets/images/bedroom-staging-modern-2.jpg",
      description: "PVC P-trap for drainage. Standard size.",
      vendor: "Coastal Building Supplies"
    },
    {
      id: "mat-030",
      title: "Water Heater - Electric 50L",
      category: "Plumbing Fittings",
      price: 18500,
      location: "Nakuru",
      condition: "New",
      featured: true,
      image: "assets/images/bed-dark-headboard-blue.jpg",
      description: "Electric water heater 50L. Reliable hot water.",
      vendor: "Rift Valley Hardware"
    },
    {
      id: "mat-031",
      title: "Pressure Pump - 0.5HP",
      category: "Plumbing Fittings",
      price: 12500,
      location: "Eldoret",
      condition: "New",
      featured: false,
      image: "assets/images/bathroom-grey-modern.jpg",
      description: "Water pressure pump. Boost water flow.",
      vendor: "Highland Building Materials"
    },
    {
      id: "mat-032",
      title: "Flexible Hose - 50cm Stainless",
      category: "Plumbing Fittings",
      price: 850,
      location: "Kiambu",
      condition: "New",
      featured: false,
      image: "assets/images/table-coffee-round-wood.jpg",
      description: "Stainless flexible hose. Durable connection.",
      vendor: "County Hardware"
    },
    {
      id: "mat-033",
      title: "Basin Waste - Pop-Up",
      category: "Plumbing Fittings",
      price: 650,
      location: "Nairobi",
      condition: "New",
      featured: false,
      image: "assets/images/bed-dark-wood-suite-1.jpg",
      description: "Pop-up basin waste. Modern mechanism.",
      vendor: "PlumbPro Kenya"
    },
    {
      id: "mat-034",
      title: "Shower Drain - Square Chrome",
      category: "Plumbing Fittings",
      price: 1200,
      location: "Westlands",
      condition: "New",
      featured: false,
      image: "assets/images/bed-burgundy-velvet-headboard.jpg",
      description: "Square chrome shower drain. Stylish finish.",
      vendor: "Elite Bathrooms"
    },
    {
      id: "mat-035",
      title: "Water Tank - 1000L Plastic",
      category: "Plumbing Fittings",
      price: 14500,
      location: "Karen",
      condition: "New",
      featured: true,
      image: "assets/images/bed-brown-panel-headboard.jpg",
      description: "1000L plastic water tank. UV stabilized.",
      vendor: "Metro Hardware Supplies"
    },
    {
      id: "mat-036",
      title: "Pipe Fittings Set - Brass",
      category: "Plumbing Fittings",
      price: 2500,
      location: "Kisumu",
      condition: "New",
      featured: false,
      image: "assets/images/bed-grey-geometric-headboard.jpg",
      description: "Assorted brass pipe fittings. Professional grade.",
      vendor: "Lake Region Hardware"
    },

    // ELECTRICAL FITTINGS (12 items)
    {
      id: "mat-037",
      title: "Socket Outlet - Double 13A",
      category: "Electrical Fittings",
      price: 450,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/bed-grey-stripe-teal-bench.jpg",
      description: "Double 13A socket outlet. Standard Kenyan.",
      vendor: "ElectroWorld Kenya"
    },
    {
      id: "mat-038",
      title: "Light Switch - 2-Gang 1-Way",
      category: "Electrical Fittings",
      price: 350,
      location: "Westlands",
      condition: "New",
      featured: false,
      image: "assets/images/tv-unit-white-gold-handles.jpg",
      description: "2-gang 1-way light switch. Modern design.",
      vendor: "ElectroWorld Kenya"
    },
    {
      id: "mat-039",
      title: "Circuit Breaker - 32A MCB",
      category: "Electrical Fittings",
      price: 850,
      location: "Karen",
      condition: "New",
      featured: false,
      image: "assets/images/tv-unit-white-oak.jpg",
      description: "32A miniature circuit breaker. Safety protection.",
      vendor: "Elite Electrical"
    },
    {
      id: "mat-040",
      title: "LED Downlight - 12W Warm White",
      category: "Electrical Fittings",
      price: 650,
      location: "Kisumu",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-grey-sectional-luxury.jpg",
      description: "12W LED downlight. Energy efficient.",
      vendor: "Lake Region Hardware"
    },
    {
      id: "mat-041",
      title: "Ceiling Rose - Plastic White",
      category: "Electrical Fittings",
      price: 150,
      location: "Mombasa",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-gold-set-curtains.jpg",
      description: "Plastic ceiling rose. Light fixture mount.",
      vendor: "Coastal Building Supplies"
    },
    {
      id: "mat-042",
      title: "Extension Cable - 10m 4-Way",
      category: "Electrical Fittings",
      price: 1850,
      location: "Nakuru",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-grey-u-shaped-teal.jpg",
      description: "10m 4-way extension cable. Heavy duty.",
      vendor: "Rift Valley Hardware"
    },
    {
      id: "mat-043",
      title: "Distribution Board - 12-Way",
      category: "Electrical Fittings",
      price: 4500,
      location: "Eldoret",
      condition: "New",
      featured: true,
      image: "assets/images/sofa-cream-sectional-set.jpg",
      description: "12-way distribution board. Main power distribution.",
      vendor: "Highland Building Materials"
    },
    {
      id: "mat-044",
      title: "Electrical Wire - 2.5mm 100m",
      category: "Electrical Fittings",
      price: 6500,
      location: "Kiambu",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-living-room-patterned.jpg",
      description: "2.5mm electrical wire 100m. Copper conductor.",
      vendor: "County Hardware"
    },
    {
      id: "mat-045",
      title: "Fan Regulator - Step",
      category: "Electrical Fittings",
      price: 450,
      location: "Nairobi",
      condition: "New",
      featured: false,
      image: "assets/images/table-coffee-hardwood-1.jpg",
      description: "Step fan speed regulator. Smooth control.",
      vendor: "ElectroWorld Kenya"
    },
    {
      id: "mat-046",
      title: "Timer Switch - Digital",
      category: "Electrical Fittings",
      price: 1250,
      location: "Westlands",
      condition: "New",
      featured: false,
      image: "assets/images/table-coffee-hardwood-2.jpg",
      description: "Digital timer switch. Automated control.",
      vendor: "Elite Electrical"
    },
    {
      id: "mat-047",
      title: "LED Panel Light - 600x600mm",
      category: "Electrical Fittings",
      price: 3500,
      location: "Karen",
      condition: "New",
      featured: true,
      image: "assets/images/2.jpg",
      description: "600x600mm LED panel. Office lighting.",
      vendor: "ElectroWorld Kenya"
    },
    {
      id: "mat-048",
      title: "Surge Protector - 6-Outlet",
      category: "Electrical Fittings",
      price: 1850,
      location: "Kisumu",
      condition: "New",
      featured: false,
      image: "assets/images/bedroom-staging-modern-1.jpg",
      description: "6-outlet surge protector. Device protection.",
      vendor: "Lake Region Hardware"
    },

    // CEMENT (8 items)
    {
      id: "mat-049",
      title: "Portland Cement - 50kg Bag",
      category: "Cement",
      price: 750,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/sofa-cream-bubble-wood-table.jpg",
      description: "Portland cement 50kg. Standard construction grade.",
      vendor: "Builders Depot Kenya"
    },
    {
      id: "mat-050",
      title: "Masonry Cement - 50kg Bag",
      category: "Cement",
      price: 850,
      location: "Westlands",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-brown-l-shaped-ottoman.jpg",
      description: "Masonry cement for plastering. Smooth finish.",
      vendor: "Builders Depot Kenya"
    },
    {
      id: "mat-051",
      title: "White Cement - 50kg Bag",
      category: "Cement",
      price: 1450,
      location: "Karen",
      condition: "New",
      featured: true,
      image: "assets/images/sofa-grey-l-shaped-teal.jpg",
      description: "White cement for decorative finishes. Premium.",
      vendor: "Elite Cement"
    },
    {
      id: "mat-052",
      title: "Rapid Set Cement - 25kg Bag",
      category: "Cement",
      price: 950,
      location: "Kisumu",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-teal-velvet-set.jpg",
      description: "Fast-setting cement. Quick repairs.",
      vendor: "Lake Region Hardware"
    },
    {
      id: "mat-053",
      title: "Waterproof Cement - 50kg Bag",
      category: "Cement",
      price: 1250,
      location: "Mombasa",
      condition: "New",
      featured: false,
      image: "assets/images/living-room-modern-orange.jpg",
      description: "Waterproof cement additive. Damp areas.",
      vendor: "Coastal Building Supplies"
    },
    {
      id: "mat-054",
      title: "Cement - 50kg Bag (Wholesale 50 bags)",
      category: "Cement",
      price: 35000,
      location: "Nakuru",
      condition: "New",
      featured: true,
      image: "assets/images/living-room-beige-cozy.jpg",
      description: "Wholesale 50 bags. Bulk discount.",
      vendor: "Rift Valley Hardware"
    },
    {
      id: "mat-055",
      title: "Refractory Cement - 25kg",
      category: "Cement",
      price: 1850,
      location: "Eldoret",
      condition: "New",
      featured: false,
      image: "assets/images/property-kitchen-dining.jpg",
      description: "Heat-resistant cement. For fireplaces.",
      vendor: "Highland Building Materials"
    },
    {
      id: "mat-056",
      title: "Cement Additive - Bonding Agent 5L",
      category: "Cement",
      price: 1850,
      location: "Kiambu",
      condition: "New",
      featured: false,
      image: "assets/images/property-living-furnished.jpg",
      description: "Cement bonding agent. Improved adhesion.",
      vendor: "County Hardware"
    },

    // TIMBER (10 items)
    {
      id: "mat-057",
      title: "Pine Timber - 2x4x6ft",
      category: "Timber",
      price: 450,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/table-nesting-black-glass-1.jpg",
      description: "Pine timber 2x4x6ft. General construction.",
      vendor: "Timber Yard Kenya"
    },
    {
      id: "mat-058",
      title: "Cypress Timber - 2x6x8ft",
      category: "Timber",
      price: 850,
      location: "Westlands",
      condition: "New",
      featured: false,
      image: "assets/images/table-nesting-black-glass-2.jpg",
      description: "Cypress timber 2x6x8ft. Roofing and framing.",
      vendor: "Timber Yard Kenya"
    },
    {
      id: "mat-059",
      title: "Mahogany Planks - 1x6x8ft",
      category: "Timber",
      price: 1850,
      location: "Karen",
      condition: "New",
      featured: true,
      image: "assets/images/sofa-cream-set-marble.jpg",
      description: "Mahogany planks. Premium finish work.",
      vendor: "Elite Timber"
    },
    {
      id: "mat-060",
      title: "Plywood Sheet - 18mm 4x8",
      category: "Timber",
      price: 3500,
      location: "Kisumu",
      condition: "New",
      featured: false,
      image: "assets/images/property-luxury-villa.jpg",
      description: "18mm plywood sheet 4x8. Cabinet making.",
      vendor: "Lake Region Hardware"
    },
    {
      id: "mat-061",
      title: "MDF Board - 16mm 4x8",
      category: "Timber",
      price: 2850,
      location: "Mombasa",
      condition: "New",
      featured: false,
      image: "assets/images/bed-dark-wood-ottomans.jpg",
      description: "16mm MDF board 4x8. Furniture making.",
      vendor: "Coastal Building Supplies"
    },
    {
      id: "mat-062",
      title: "Treated Poles - 4-inch 10ft",
      category: "Timber",
      price: 650,
      location: "Nakuru",
      condition: "New",
      featured: false,
      image: "assets/images/bedroom-staging-modern-2.jpg",
      description: "Treated poles 4-inch 10ft. Fencing.",
      vendor: "Rift Valley Hardware"
    },
    {
      id: "mat-063",
      title: "Hardwood Flooring - Oak 90x19mm",
      category: "Timber",
      price: 4500,
      location: "Eldoret",
      condition: "New",
      featured: true,
      image: "assets/images/bed-dark-headboard-blue.jpg",
      description: "Oak hardwood flooring. Premium finish.",
      vendor: "Highland Building Materials"
    },
    {
      id: "mat-064",
      title: "Particle Board - 12mm 4x8",
      category: "Timber",
      price: 1850,
      location: "Kiambu",
      condition: "New",
      featured: false,
      image: "assets/images/bathroom-grey-modern.jpg",
      description: "12mm particle board. Budget shelving.",
      vendor: "County Hardware"
    },
    {
      id: "mat-065",
      title: "Blockboard - 18mm 4x8",
      category: "Timber",
      price: 3200,
      location: "Nairobi",
      condition: "New",
      featured: false,
      image: "assets/images/table-coffee-round-wood.jpg",
      description: "18mm blockboard. Door making.",
      vendor: "Timber Yard Kenya"
    },
    {
      id: "mat-066",
      title: "Veneer Sheets - Assorted",
      category: "Timber",
      price: 2500,
      location: "Westlands",
      condition: "New",
      featured: false,
      image: "assets/images/bed-dark-wood-suite-1.jpg",
      description: "Assorted wood veneer sheets. Decorative finish.",
      vendor: "Elite Timber"
    },

    // BOARDS (8 items)
    {
      id: "mat-067",
      title: "Gypsum Board - 12mm 4x8",
      category: "Boards",
      price: 1250,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/bed-burgundy-velvet-headboard.jpg",
      description: "12mm gypsum board 4x8. Ceiling and partitioning.",
      vendor: "Gypsum Experts Kenya"
    },
    {
      id: "mat-068",
      title: "Gypsum Board - 9mm 4x8",
      category: "Boards",
      price: 950,
      location: "Karen",
      condition: "New",
      featured: false,
      image: "assets/images/bed-brown-panel-headboard.jpg",
      description: "9mm gypsum board 4x8. Lightweight partitioning.",
      vendor: "Gypsum Experts Kenya"
    },
    {
      id: "mat-069",
      title: "Cement Board - 12mm 4x8",
      category: "Boards",
      price: 1850,
      location: "Westlands",
      condition: "New",
      featured: true,
      image: "assets/images/bed-grey-geometric-headboard.jpg",
      description: "12mm cement board. Wet areas and exterior.",
      vendor: "Metro Hardware Supplies"
    },
    {
      id: "mat-070",
      title: "Insulation Board - 50mm 4x8",
      category: "Boards",
      price: 2850,
      location: "Kisumu",
      condition: "New",
      featured: false,
      image: "assets/images/bed-grey-stripe-teal-bench.jpg",
      description: "50mm insulation board. Thermal and sound.",
      vendor: "Lake Region Hardware"
    },
    {
      id: "mat-071",
      title: "Fiber Cement Board - 6mm 4x8",
      category: "Boards",
      price: 1450,
      location: "Mombasa",
      condition: "New",
      featured: false,
      image: "assets/images/tv-unit-white-gold-handles.jpg",
      description: "6mm fiber cement board. Durable cladding.",
      vendor: "Coastal Building Supplies"
    },
    {
      id: "mat-072",
      title: "Acoustic Board - 12mm 4x8",
      category: "Boards",
      price: 3200,
      location: "Nakuru",
      condition: "New",
      featured: false,
      image: "assets/images/tv-unit-white-oak.jpg",
      description: "12mm acoustic board. Sound absorption.",
      vendor: "Rift Valley Hardware"
    },
    {
      id: "mat-073",
      title: "OSB Board - 18mm 4x8",
      category: "Boards",
      price: 2450,
      location: "Eldoret",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-grey-sectional-luxury.jpg",
      description: "18mm OSB board. Structural sheathing.",
      vendor: "Highland Building Materials"
    },
    {
      id: "mat-074",
      title: "Fire-Rated Board - 12mm 4x8",
      category: "Boards",
      price: 3850,
      location: "Kiambu",
      condition: "New",
      featured: true,
      image: "assets/images/sofa-gold-set-curtains.jpg",
      description: "12mm fire-rated board. Safety compliance.",
      vendor: "County Hardware"
    },

    // ROOFING SHEETS (8 items)
    {
      id: "mat-075",
      title: "Corrugated Iron Sheets - 3m Gauge 30",
      category: "Roofing Sheets",
      price: 1850,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/sofa-grey-u-shaped-teal.jpg",
      description: "3m corrugated iron sheets gauge 30. Standard roofing.",
      vendor: "Roofing Masters Kenya"
    },
    {
      id: "mat-076",
      title: "Box Profile Sheets - 3m Gauge 28",
      category: "Roofing Sheets",
      price: 2450,
      location: "Westlands",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-cream-sectional-set.jpg",
      description: "3m box profile sheets gauge 28. Modern look.",
      vendor: "Roofing Masters Kenya"
    },
    {
      id: "mat-077",
      title: "Stone-Coated Tiles - 2.4m",
      category: "Roofing Sheets",
      price: 4500,
      location: "Karen",
      condition: "New",
      featured: true,
      image: "assets/images/sofa-living-room-patterned.jpg",
      description: "Stone-coated roofing tiles. Premium appearance.",
      vendor: "Elite Roofing"
    },
    {
      id: "mat-078",
      title: "Polycarbonate Sheets - Clear 2m",
      category: "Roofing Sheets",
      price: 1850,
      location: "Kisumu",
      condition: "New",
      featured: false,
      image: "assets/images/table-coffee-hardwood-1.jpg",
      description: "Clear polycarbonate sheets. Natural lighting.",
      vendor: "Lake Region Hardware"
    },
    {
      id: "mat-079",
      title: "Guttering System - PVC Brown",
      category: "Roofing Sheets",
      price: 450,
      location: "Mombasa",
      condition: "New",
      featured: false,
      image: "assets/images/table-coffee-hardwood-2.jpg",
      description: "PVC guttering system brown. Water drainage.",
      vendor: "Coastal Building Supplies"
    },
    {
      id: "mat-080",
      title: "Ridge Caps - Brown 3m",
      category: "Roofing Sheets",
      price: 650,
      location: "Nakuru",
      condition: "New",
      featured: false,
      image: "assets/images/2.jpg",
      description: "Brown ridge caps 3m. Roof finishing.",
      vendor: "Rift Valley Hardware"
    },
    {
      id: "mat-081",
      title: "Flashings - Valley 3m",
      category: "Roofing Sheets",
      price: 550,
      location: "Eldoret",
      condition: "New",
      featured: false,
      image: "assets/images/bedroom-staging-modern-1.jpg",
      description: "Valley flashings 3m. Water protection.",
      vendor: "Highland Building Materials"
    },
    {
      id: "mat-082",
      title: "Roofing Nails - 1kg Box",
      category: "Roofing Sheets",
      price: 450,
      location: "Kiambu",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-cream-bubble-wood-table.jpg",
      description: "Roofing nails 1kg. Secure fastening.",
      vendor: "County Hardware"
    },

    // GYPSUM MATERIALS (8 items)
    {
      id: "mat-083",
      title: "Gypsum Plaster - 50kg Bag",
      category: "Gypsum Materials",
      price: 1850,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/sofa-brown-l-shaped-ottoman.jpg",
      description: "Gypsum plaster 50kg. Wall finishing.",
      vendor: "Gypsum Experts Kenya"
    },
    {
      id: "mat-084",
      title: "Jointing Compound - 25kg",
      category: "Gypsum Materials",
      price: 1250,
      location: "Westlands",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-grey-l-shaped-teal.jpg",
      description: "Jointing compound 25kg. Board finishing.",
      vendor: "Gypsum Experts Kenya"
    },
    {
      id: "mat-085",
      title: "Corner Bead - Metal 2.4m",
      category: "Gypsum Materials",
      price: 150,
      location: "Karen",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-teal-velvet-set.jpg",
      description: "Metal corner bead 2.4m. Edge protection.",
      vendor: "Elite Gypsum"
    },
    {
      id: "mat-086",
      title: "Ceiling Channels - Galvanized 3m",
      category: "Gypsum Materials",
      price: 350,
      location: "Kisumu",
      condition: "New",
      featured: false,
      image: "assets/images/living-room-modern-orange.jpg",
      description: "Galvanized ceiling channels 3m. Suspension.",
      vendor: "Lake Region Hardware"
    },
    {
      id: "mat-087",
      title: "Ceiling Tees - Galvanized 0.6m",
      category: "Gypsum Materials",
      price: 85,
      location: "Mombasa",
      condition: "New",
      featured: false,
      image: "assets/images/living-room-beige-cozy.jpg",
      description: "Galvanized ceiling tees 0.6m. Grid system.",
      vendor: "Coastal Building Supplies"
    },
    {
      id: "mat-088",
      title: "Gypsum Screws - 1000pcs",
      category: "Gypsum Materials",
      price: 650,
      location: "Nakuru",
      condition: "New",
      featured: false,
      image: "assets/images/property-kitchen-dining.jpg",
      description: "Gypsum screws 1000pcs. Board fastening.",
      vendor: "Rift Valley Hardware"
    },
    {
      id: "mat-089",
      title: "Pop Corners - PVC White",
      category: "Gypsum Materials",
      price: 250,
      location: "Eldoret",
      condition: "New",
      featured: false,
      image: "assets/images/property-living-furnished.jpg",
      description: "PVC pop corners white. Decorative finishing.",
      vendor: "Highland Building Materials"
    },
    {
      id: "mat-090",
      title: "Gypsum Cornice - 4m Length",
      category: "Gypsum Materials",
      price: 850,
      location: "Kiambu",
      condition: "New",
      featured: true,
      image: "assets/images/table-nesting-black-glass-1.jpg",
      description: "Gypsum cornice 4m. Elegant ceiling border.",
      vendor: "County Hardware"
    },

    // TOOLS (10 items)
    {
      id: "mat-091",
      title: "Power Drill - 18V Cordless",
      category: "Tools",
      price: 8500,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/table-nesting-black-glass-2.jpg",
      description: "18V cordless power drill. Versatile drilling.",
      vendor: "ToolPro Kenya"
    },
    {
      id: "mat-092",
      title: "Circular Saw - 7-1/4 inch",
      category: "Tools",
      price: 12500,
      location: "Westlands",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-cream-set-marble.jpg",
      description: "7-1/4 inch circular saw. Wood cutting.",
      vendor: "ToolPro Kenya"
    },
    {
      id: "mat-093",
      title: "Angle Grinder - 1000W",
      category: "Tools",
      price: 4500,
      location: "Karen",
      condition: "New",
      featured: false,
      image: "assets/images/property-luxury-villa.jpg",
      description: "1000W angle grinder. Cutting and grinding.",
      vendor: "Elite Tools"
    },
    {
      id: "mat-094",
      title: "Hammer Drill - SDS Plus",
      category: "Tools",
      price: 7500,
      location: "Kisumu",
      condition: "New",
      featured: false,
      image: "assets/images/bed-dark-wood-ottomans.jpg",
      description: "SDS Plus hammer drill. Concrete drilling.",
      vendor: "Lake Region Hardware"
    },
    {
      id: "mat-095",
      title: "Jigsaw - 500W",
      category: "Tools",
      price: 5500,
      location: "Mombasa",
      condition: "New",
      featured: false,
      image: "assets/images/bedroom-staging-modern-2.jpg",
      description: "500W jigsaw. Curved cutting.",
      vendor: "Coastal Building Supplies"
    },
    {
      id: "mat-096",
      title: "Measuring Tape - 10m",
      category: "Tools",
      price: 450,
      location: "Nakuru",
      condition: "New",
      featured: false,
      image: "assets/images/bed-dark-headboard-blue.jpg",
      description: "10m measuring tape. Accurate measurement.",
      vendor: "Rift Valley Hardware"
    },
    {
      id: "mat-097",
      title: "Spirit Level - 1200mm",
      category: "Tools",
      price: 850,
      location: "Eldoret",
      condition: "New",
      featured: false,
      image: "assets/images/bathroom-grey-modern.jpg",
      description: "1200mm spirit level. Precision leveling.",
      vendor: "Highland Building Materials"
    },
    {
      id: "mat-098",
      title: "Tool Belt - Heavy Duty",
      category: "Tools",
      price: 1250,
      location: "Kiambu",
      condition: "New",
      featured: false,
      image: "assets/images/table-coffee-round-wood.jpg",
      description: "Heavy duty tool belt. Convenient storage.",
      vendor: "County Hardware"
    },
    {
      id: "mat-099",
      title: "Safety Helmet - Yellow",
      category: "Tools",
      price: 450,
      location: "Nairobi",
      condition: "New",
      featured: false,
      image: "assets/images/bed-dark-wood-suite-1.jpg",
      description: "Yellow safety helmet. Head protection.",
      vendor: "ToolPro Kenya"
    },
    {
      id: "mat-100",
      title: "Toolbox - Large Metal",
      category: "Tools",
      price: 1850,
      location: "Westlands",
      condition: "New",
      featured: false,
      image: "assets/images/bed-burgundy-velvet-headboard.jpg",
      description: "Large metal toolbox. Secure storage.",
      vendor: "Elite Tools"
    },

    // MACHINES (8 items)
    {
      id: "mat-101",
      title: "Concrete Mixer - 150L",
      category: "Machines",
      price: 45000,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/bed-brown-panel-headboard.jpg",
      description: "150L concrete mixer. Construction essential.",
      vendor: "Heavy Machinery Kenya"
    },
    {
      id: "mat-102",
      title: "Tile Cutter - Manual 600mm",
      category: "Machines",
      price: 8500,
      location: "Karen",
      condition: "New",
      featured: false,
      image: "assets/images/bed-grey-geometric-headboard.jpg",
      description: "600mm manual tile cutter. Precision cutting.",
      vendor: "Tile Masters Kenya"
    },
    {
      id: "mat-103",
      title: "Power Saw - Table 10 inch",
      category: "Machines",
      price: 28500,
      location: "Westlands",
      condition: "New",
      featured: true,
      image: "assets/images/bed-grey-stripe-teal-bench.jpg",
      description: "10 inch table saw. Accurate cuts.",
      vendor: "Woodcraft Kenya"
    },
    {
      id: "mat-104",
      title: "Compressor - 50L",
      category: "Machines",
      price: 35000,
      location: "Kisumu",
      condition: "New",
      featured: false,
      image: "assets/images/tv-unit-white-gold-handles.jpg",
      description: "50L air compressor. Pneumatic tools.",
      vendor: "Lake Region Hardware"
    },
    {
      id: "mat-105",
      title: "Generator - 5kVA Petrol",
      category: "Machines",
      price: 65000,
      location: "Mombasa",
      condition: "New",
      featured: true,
      image: "assets/images/tv-unit-white-oak.jpg",
      description: "5kVA petrol generator. Backup power.",
      vendor: "Coastal Building Supplies"
    },
    {
      id: "mat-106",
      title: "Water Pump - 1 inch Electric",
      category: "Machines",
      price: 8500,
      location: "Nakuru",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-grey-sectional-luxury.jpg",
      description: "1 inch electric water pump. Irrigation.",
      vendor: "Rift Valley Hardware"
    },
    {
      id: "mat-107",
      title: "Plate Compactor - Petrol",
      category: "Machines",
      price: 45000,
      location: "Eldoret",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-gold-set-curtains.jpg",
      description: "Petrol plate compactor. Soil compaction.",
      vendor: "Highland Building Materials"
    },
    {
      id: "mat-108",
      title: "Welder - Inverter 200A",
      category: "Machines",
      price: 28500,
      location: "Kiambu",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-grey-u-shaped-teal.jpg",
      description: "200A inverter welder. Metal fabrication.",
      vendor: "County Hardware"
    },

    // LIGHTING (8 items)
    {
      id: "mat-109",
      title: "LED Bulb - 12W E27 Warm",
      category: "Lighting",
      price: 350,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/sofa-cream-sectional-set.jpg",
      description: "12W LED bulb E27 warm white. Energy saving.",
      vendor: "Lighting Solutions Kenya"
    },
    {
      id: "mat-110",
      title: "Ceiling Light - Modern LED",
      category: "Lighting",
      price: 4500,
      location: "Westlands",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-living-room-patterned.jpg",
      description: "Modern LED ceiling light. Contemporary design.",
      vendor: "Lighting Solutions Kenya"
    },
    {
      id: "mat-111",
      title: "Outdoor Wall Light - IP65",
      category: "Lighting",
      price: 1850,
      location: "Karen",
      condition: "New",
      featured: false,
      image: "assets/images/table-coffee-hardwood-1.jpg",
      description: "IP65 outdoor wall light. Weatherproof.",
      vendor: "Elite Lighting"
    },
    {
      id: "mat-112",
      title: "Spotlight - GU10 3W",
      category: "Lighting",
      price: 650,
      location: "Kisumu",
      condition: "New",
      featured: false,
      image: "assets/images/table-coffee-hardwood-2.jpg",
      description: "3W GU10 spotlight. Accent lighting.",
      vendor: "Lake Region Hardware"
    },
    {
      id: "mat-113",
      title: "Tube Light - 4ft LED",
      category: "Lighting",
      price: 850,
      location: "Mombasa",
      condition: "New",
      featured: false,
      image: "assets/images/2.jpg",
      description: "4ft LED tube light. Office lighting.",
      vendor: "Coastal Building Supplies"
    },
    {
      id: "mat-114",
      title: "Garden Light - Solar LED",
      category: "Lighting",
      price: 1250,
      location: "Nakuru",
      condition: "New",
      featured: false,
      image: "assets/images/bedroom-staging-modern-1.jpg",
      description: "Solar LED garden light. Outdoor decoration.",
      vendor: "Rift Valley Hardware"
    },
    {
      id: "mat-115",
      title: "Chandelier - 8-Light Crystal",
      category: "Lighting",
      price: 18500,
      location: "Eldoret",
      condition: "New",
      featured: true,
      image: "assets/images/sofa-cream-bubble-wood-table.jpg",
      description: "8-light crystal chandelier. Luxury lighting.",
      vendor: "Elite Lighting"
    },
    {
      id: "mat-116",
      title: "Emergency Light - LED",
      category: "Lighting",
      price: 2450,
      location: "Kiambu",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-brown-l-shaped-ottoman.jpg",
      description: "LED emergency light. Backup illumination.",
      vendor: "County Hardware"
    },

    // BATHROOM FITTINGS (8 items)
    {
      id: "mat-117",
      title: "Wash Basin - Ceramic Oval",
      category: "Bathroom Fittings",
      price: 4500,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/sofa-grey-l-shaped-teal.jpg",
      description: "Ceramic oval wash basin. Classic design.",
      vendor: "Elite Bathrooms"
    },
    {
      id: "mat-118",
      title: "Toilet Suite - Close Coupled",
      category: "Bathroom Fittings",
      price: 8500,
      location: "Westlands",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-teal-velvet-set.jpg",
      description: "Close coupled toilet suite. Complete set.",
      vendor: "Elite Bathrooms"
    },
    {
      id: "mat-119",
      title: "Shower Tray - Quadrant 900mm",
      category: "Bathroom Fittings",
      price: 6500,
      location: "Karen",
      condition: "New",
      featured: false,
      image: "assets/images/living-room-modern-orange.jpg",
      description: "900mm quadrant shower tray. Corner fitting.",
      vendor: "PlumbPro Kenya"
    },
    {
      id: "mat-120",
      title: "Bathroom Mirror - LED Backlit",
      category: "Bathroom Fittings",
      price: 5500,
      location: "Kisumu",
      condition: "New",
      featured: false,
      image: "assets/images/living-room-beige-cozy.jpg",
      description: "LED backlit bathroom mirror. Modern touch.",
      vendor: "Lake Region Hardware"
    },
    {
      id: "mat-121",
      title: "Towel Rail - Heated",
      category: "Bathroom Fittings",
      price: 4500,
      location: "Mombasa",
      condition: "New",
      featured: false,
      image: "assets/images/property-kitchen-dining.jpg",
      description: "Heated towel rail. Warm towels.",
      vendor: "Coastal Building Supplies"
    },
    {
      id: "mat-122",
      title: "Soap Dispenser - Wall Mounted",
      category: "Bathroom Fittings",
      price: 850,
      location: "Nakuru",
      condition: "New",
      featured: false,
      image: "assets/images/property-living-furnished.jpg",
      description: "Wall mounted soap dispenser. Hygiene.",
      vendor: "Rift Valley Hardware"
    },
    {
      id: "mat-123",
      title: "Toilet Roll Holder - Chrome",
      category: "Bathroom Fittings",
      price: 450,
      location: "Eldoret",
      condition: "New",
      featured: false,
      image: "assets/images/table-nesting-black-glass-1.jpg",
      description: "Chrome toilet roll holder. Stylish.",
      vendor: "Highland Building Materials"
    },
    {
      id: "mat-124",
      title: "Bathroom Cabinet - Wall Mirror",
      category: "Bathroom Fittings",
      price: 6500,
      location: "Kiambu",
      condition: "New",
      featured: true,
      image: "assets/images/table-nesting-black-glass-2.jpg",
      description: "Mirror cabinet with storage. Organized.",
      vendor: "County Hardware"
    },

    // KITCHEN FITTINGS (8 items)
    {
      id: "mat-125",
      title: "Kitchen Sink - Stainless Double",
      category: "Kitchen Fittings",
      price: 6500,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/sofa-cream-set-marble.jpg",
      description: "Double bowl stainless sink. Practical.",
      vendor: "Elite Kitchens"
    },
    {
      id: "mat-126",
      title: "Kitchen Faucet - Pull-Out Spray",
      category: "Kitchen Fittings",
      price: 5500,
      location: "Westlands",
      condition: "New",
      featured: false,
      image: "assets/images/property-luxury-villa.jpg",
      description: "Pull-out spray kitchen faucet. Versatile.",
      vendor: "PlumbPro Kenya"
    },
    {
      id: "mat-127",
      title: "Cooker Hood - Chimney 900mm",
      category: "Kitchen Fittings",
      price: 18500,
      location: "Karen",
      condition: "New",
      featured: true,
      image: "assets/images/bed-dark-wood-ottomans.jpg",
      description: "900mm chimney cooker hood. Ventilation.",
      vendor: "Elite Kitchens"
    },
    {
      id: "mat-128",
      title: "Kitchen Handles - Chrome Set",
      category: "Kitchen Fittings",
      price: 1250,
      location: "Kisumu",
      condition: "New",
      featured: false,
      image: "assets/images/bedroom-staging-modern-2.jpg",
      description: "Chrome handle set. Modern upgrade.",
      vendor: "Lake Region Hardware"
    },
    {
      id: "mat-129",
      title: "Under-Cabinet Lighting - LED Strip",
      category: "Kitchen Fittings",
      price: 2850,
      location: "Mombasa",
      condition: "New",
      featured: false,
      image: "assets/images/bed-dark-headboard-blue.jpg",
      description: "LED strip lighting. Task lighting.",
      vendor: "Coastal Building Supplies"
    },
    {
      id: "mat-130",
      title: "Kitchen Organizer - Pull-Out",
      category: "Kitchen Fittings",
      price: 3500,
      location: "Nakuru",
      condition: "New",
      featured: false,
      image: "assets/images/bathroom-grey-modern.jpg",
      description: "Pull-out organizer. Space saving.",
      vendor: "Rift Valley Hardware"
    },
    {
      id: "mat-131",
      title: "Trash Bin - Pull-Out 15L",
      category: "Kitchen Fittings",
      price: 1850,
      location: "Eldoret",
      condition: "New",
      featured: false,
      image: "assets/images/table-coffee-round-wood.jpg",
      description: "15L pull-out trash bin. Hidden storage.",
      vendor: "Highland Building Materials"
    },
    {
      id: "mat-132",
      title: "Kitchen Sink Strainer - Stainless",
      category: "Kitchen Fittings",
      price: 450,
      location: "Kiambu",
      condition: "New",
      featured: false,
      image: "assets/images/bed-dark-wood-suite-1.jpg",
      description: "Stainless sink strainer. Drain protection.",
      vendor: "County Hardware"
    },

    // CONSTRUCTION MATERIALS (8 items)
    {
      id: "mat-133",
      title: "Sand - River per ton",
      category: "Construction Materials",
      price: 2500,
      location: "Nairobi",
      condition: "New",
      featured: true,
      image: "assets/images/bed-burgundy-velvet-headboard.jpg",
      description: "River sand per ton. Construction grade.",
      vendor: "Builders Depot Kenya"
    },
    {
      id: "mat-134",
      title: "Ballast - Quarry per ton",
      category: "Construction Materials",
      price: 3500,
      location: "Westlands",
      condition: "New",
      featured: false,
      image: "assets/images/bed-brown-panel-headboard.jpg",
      description: "Quarry ballast per ton. Concrete aggregate.",
      vendor: "Builders Depot Kenya"
    },
    {
      id: "mat-135",
      title: "Building Stones - 6x9 per truck",
      category: "Construction Materials",
      price: 25000,
      location: "Karen",
      condition: "New",
      featured: true,
      image: "assets/images/bed-grey-geometric-headboard.jpg",
      description: "6x9 building stones per truckload. Foundation.",
      vendor: "Elite Stone Suppliers"
    },
    {
      id: "mat-136",
      title: "Steel Bars - 16mm per ton",
      category: "Construction Materials",
      price: 85000,
      location: "Kisumu",
      condition: "New",
      featured: false,
      image: "assets/images/bed-grey-stripe-teal-bench.jpg",
      description: "16mm steel bars per ton. Reinforcement.",
      vendor: "Lake Region Hardware"
    },
    {
      id: "mat-137",
      title: "Wire Mesh - 4x4 50m roll",
      category: "Construction Materials",
      price: 6500,
      location: "Mombasa",
      condition: "New",
      featured: false,
      image: "assets/images/tv-unit-white-gold-handles.jpg",
      description: "4x4 wire mesh 50m. Concrete reinforcement.",
      vendor: "Coastal Building Supplies"
    },
    {
      id: "mat-138",
      title: "Bricks - Red per 1000",
      category: "Construction Materials",
      price: 15000,
      location: "Nakuru",
      condition: "New",
      featured: false,
      image: "assets/images/tv-unit-white-oak.jpg",
      description: "Red bricks per 1000. Wall construction.",
      vendor: "Rift Valley Hardware"
    },
    {
      id: "mat-139",
      title: "Concrete Blocks - 6-inch per 100",
      category: "Construction Materials",
      price: 8500,
      location: "Eldoret",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-grey-sectional-luxury.jpg",
      description: "6-inch concrete blocks per 100. Fast construction.",
      vendor: "Highland Building Materials"
    },
    {
      id: "mat-140",
      title: "Gravel - Crushed per ton",
      category: "Construction Materials",
      price: 3000,
      location: "Kiambu",
      condition: "New",
      featured: false,
      image: "assets/images/sofa-gold-set-curtains.jpg",
      description: "Crushed gravel per ton. Driveway and concrete.",
      vendor: "County Hardware"
    }
  ],

  // Categories for filtering
  categories: [
    "Paint",
    "Tiles",
    "Plumbing Fittings",
    "Electrical Fittings",
    "Cement",
    "Timber",
    "Boards",
    "Roofing Sheets",
    "Gypsum Materials",
    "Tools",
    "Machines",
    "Lighting",
    "Bathroom Fittings",
    "Kitchen Fittings",
    "Construction Materials"
  ],

  // Locations for filtering
  locations: [
    "Nairobi",
    "Westlands",
    "Karen",
    "Kisumu",
    "Mombasa",
    "Nakuru",
    "Eldoret",
    "Kiambu"
  ],

  // Price ranges for filtering
  priceRanges: [
    { min: 0, max: 1000, label: "Under KSh 1,000" },
    { min: 1000, max: 5000, label: "KSh 1,000 - KSh 5,000" },
    { min: 5000, max: 20000, label: "KSh 5,000 - KSh 20,000" },
    { min: 20000, max: 999999, label: "KSh 20,000+" }
  ]
};
