/**
 * FURNOSTYLES — REAL ESTATE DEMO DATA
 * =================================
 * File: shared/demo-data/property-demo.js
 * Purpose: Demo real estate properties for marketplace testing
 * 
 * This is TEST/DUMMY data for demonstration purposes only.
 * No real payments, no real users, no real transactions.
 */

window.FurnostylesPropertyDemo = {
  properties: [
    // APARTMENTS (10 items)
    {
      id: "prop-001",
      title: "2-Bedroom Apartment - Kilimani",
      category: "Apartments",
      price: 65000,
      priceType: "rent",
      location: "Kilimani, Nairobi",
      bedrooms: 2,
      bathrooms: 2,
      featured: true,
      image: "assets/images/bed-burgundy-velvet-headboard.jpg",
      description: "Modern 2-bedroom apartment in Kilimani. Spacious, secure, with amenities.",
      agent: "Prime Property Hub"
    },
    {
      id: "prop-002",
      title: "3-Bedroom Apartment - Westlands",
      category: "Apartments",
      price: 85000,
      priceType: "rent",
      location: "Westlands, Nairobi",
      bedrooms: 3,
      bathrooms: 2,
      featured: true,
      image: "assets/images/bed-brown-panel-headboard.jpg",
      description: "Luxury 3-bedroom apartment in Westlands. Pool, gym, parking.",
      agent: "Prime Property Hub"
    },
    {
      id: "prop-003",
      title: "1-Bedroom Studio - Karen",
      category: "Apartments",
      price: 45000,
      priceType: "rent",
      location: "Karen, Nairobi",
      bedrooms: 1,
      bathrooms: 1,
      featured: false,
      image: "assets/images/bed-grey-geometric-headboard.jpg",
      description: "Cozy 1-bedroom studio in Karen. Quiet neighborhood, secure.",
      agent: "Elite Real Estate"
    },
    {
      id: "prop-004",
      title: "4-Bedroom Penthouse - Mombasa",
      category: "Apartments",
      price: 150000,
      priceType: "rent",
      location: "Nyali, Mombasa",
      bedrooms: 4,
      bathrooms: 3,
      featured: true,
      image: "assets/images/bed-grey-stripe-teal-bench.jpg",
      description: "Ocean-view penthouse in Nyali. 4 bedrooms, luxury finish.",
      agent: "Coastal Properties"
    },
    {
      id: "prop-005",
      title: "2-Bedroom Apartment - Kisumu",
      category: "Apartments",
      price: 35000,
      priceType: "rent",
      location: "Milimani, Kisumu",
      bedrooms: 2,
      bathrooms: 1,
      featured: false,
      image: "assets/images/tv-unit-white-gold-handles.jpg",
      description: "Affordable 2-bedroom in Milimani. Near town center.",
      agent: "Lake Region Properties"
    },
    {
      id: "prop-006",
      title: "3-Bedroom Apartment - Nakuru",
      category: "Apartments",
      price: 45000,
      priceType: "rent",
      location: "Milimani, Nakuru",
      bedrooms: 3,
      bathrooms: 2,
      featured: false,
      image: "assets/images/tv-unit-white-oak.jpg",
      description: "Modern 3-bedroom in Nakuru. Secure compound, parking.",
      agent: "Rift Valley Real Estate"
    },
    {
      id: "prop-007",
      title: "1-Bedroom Apartment - Eldoret",
      category: "Apartments",
      price: 25000,
      priceType: "rent",
      location: "Eldoret Town",
      bedrooms: 1,
      bathrooms: 1,
      featured: false,
      image: "assets/images/sofa-grey-sectional-luxury.jpg",
      description: "Budget 1-bedroom in Eldoret. Central location.",
      agent: "Highland Properties"
    },
    {
      id: "prop-008",
      title: "2-Bedroom Apartment - Syokimau",
      category: "Apartments",
      price: 40000,
      priceType: "rent",
      location: "Syokimau, Nairobi",
      bedrooms: 2,
      bathrooms: 1,
      featured: false,
      image: "assets/images/sofa-gold-set-curtains.jpg",
      description: "Modern apartment near SGR station. Commuter friendly.",
      agent: "Prime Property Hub"
    },
    {
      id: "prop-009",
      title: "3-Bedroom Apartment - Ruaka",
      category: "Apartments",
      price: 55000,
      priceType: "rent",
      location: "Ruaka, Nairobi",
      bedrooms: 3,
      bathrooms: 2,
      featured: false,
      image: "assets/images/sofa-grey-u-shaped-teal.jpg",
      description: "Spacious 3-bedroom in Ruaka. Growing area, good access.",
      agent: "Elite Real Estate"
    },
    {
      id: "prop-010",
      title: "4-Bedroom Apartment - Ruiru",
      category: "Apartments",
      price: 60000,
      priceType: "rent",
      location: "Ruiru, Kiambu",
      bedrooms: 4,
      bathrooms: 3,
      featured: false,
      image: "assets/images/sofa-cream-sectional-set.jpg",
      description: "Family apartment in Ruiru. Near Thika Road.",
      agent: "County Properties"
    },

    // AIRBNB UNITS (8 items)
    {
      id: "prop-011",
      title: "Airbnb Unit - Karen Villa",
      category: "Airbnb Units",
      price: 12000,
      priceType: "per night",
      location: "Karen, Nairobi",
      bedrooms: 3,
      bathrooms: 2,
      featured: true,
      image: "assets/images/sofa-living-room-patterned.jpg",
      description: "Luxury villa for Airbnb. Pool, garden, security.",
      agent: "Airbnb Kenya Experts"
    },
    {
      id: "prop-012",
      title: "Airbnb Studio - Westlands",
      category: "Airbnb Units",
      price: 6500,
      priceType: "per night",
      location: "Westlands, Nairobi",
      bedrooms: 1,
      bathrooms: 1,
      featured: false,
      image: "assets/images/table-coffee-hardwood-1.jpg",
      description: "Modern studio for short stays. Near malls and restaurants.",
      agent: "Airbnb Kenya Experts"
    },
    {
      id: "prop-013",
      title: "Airbnb Apartment - Diani",
      category: "Airbnb Units",
      price: 15000,
      priceType: "per night",
      location: "Diani, Mombasa",
      bedrooms: 2,
      bathrooms: 2,
      featured: true,
      image: "assets/images/table-coffee-hardwood-2.jpg",
      description: "Beachfront apartment. Ocean views, direct beach access.",
      agent: "Coastal Properties"
    },
    {
      id: "prop-014",
      title: "Airbnb Cottage - Naivasha",
      category: "Airbnb Units",
      price: 18000,
      priceType: "per night",
      location: "Naivasha",
      bedrooms: 4,
      bathrooms: 3,
      featured: false,
      image: "assets/images/2.jpg",
      description: "Lake view cottage. Perfect for groups, retreats.",
      agent: "Rift Valley Real Estate"
    },
    {
      id: "prop-015",
      title: "Airbnb Loft - Kilimani",
      category: "Airbnb Units",
      price: 8500,
      priceType: "per night",
      location: "Kilimani, Nairobi",
      bedrooms: 1,
      bathrooms: 1,
      featured: false,
      image: "assets/images/bedroom-staging-modern-1.jpg",
      description: "Trendy loft apartment. City views, modern amenities.",
      agent: "Airbnb Kenya Experts"
    },
    {
      id: "prop-016",
      title: "Airbnb House - Nanyuki",
      category: "Airbnb Units",
      price: 25000,
      priceType: "per night",
      location: "Nanyuki",
      bedrooms: 5,
      bathrooms: 4,
      featured: true,
      image: "assets/images/sofa-cream-bubble-wood-table.jpg",
      description: "Mountain retreat house. Mt. Kenya views, fireplace.",
      agent: "Highland Properties"
    },
    {
      id: "prop-017",
      title: "Airbnb Apartment - Kisumu",
      category: "Airbnb Units",
      price: 7000,
      priceType: "per night",
      location: "Milimani, Kisumu",
      bedrooms: 2,
      bathrooms: 1,
      featured: false,
      image: "assets/images/sofa-brown-l-shaped-ottoman.jpg",
      description: "Lake Victoria view apartment. Affordable luxury.",
      agent: "Lake Region Properties"
    },
    {
      id: "prop-018",
      title: "Airbnb Suite - Karen",
      category: "Airbnb Units",
      price: 10000,
      priceType: "per night",
      location: "Karen, Nairobi",
      bedrooms: 2,
      bathrooms: 2,
      featured: false,
      image: "assets/images/sofa-grey-l-shaped-teal.jpg",
      description: "Private suite in Karen. Garden, security, parking.",
      agent: "Airbnb Kenya Experts"
    },

    // LAND (8 items)
    {
      id: "prop-019",
      title: "1/8 Acre Plot - Karen",
      category: "Land",
      price: 15000000,
      priceType: "sale",
      location: "Karen, Nairobi",
      bedrooms: 0,
      bathrooms: 0,
      featured: true,
      image: "assets/images/sofa-teal-velvet-set.jpg",
      description: "Prime 1/8 acre plot in Karen. Ready to build, title deed ready.",
      agent: "Prime Property Hub"
    },
    {
      id: "prop-020",
      title: "50x100 Plot - Kitengela",
      category: "Land",
      price: 2500000,
      priceType: "sale",
      location: "Kitengela, Kajiado",
      bedrooms: 0,
      bathrooms: 0,
      featured: false,
      image: "assets/images/living-room-modern-orange.jpg",
      description: "50x100 plot in Kitengela. Near highway, utilities available.",
      agent: "Elite Real Estate"
    },
    {
      id: "prop-021",
      title: "5 Acres - Nanyuki",
      category: "Land",
      price: 25000000,
      priceType: "sale",
      location: "Nanyuki",
      bedrooms: 0,
      bathrooms: 0,
      featured: true,
      image: "assets/images/living-room-beige-cozy.jpg",
      description: "5 acres in Nanyuki. Agricultural land, water available.",
      agent: "Highland Properties"
    },
    {
      id: "prop-022",
      title: "1 Acre - Diani",
      category: "Land",
      price: 35000000,
      priceType: "sale",
      location: "Diani, Mombasa",
      bedrooms: 0,
      bathrooms: 0,
      featured: false,
      image: "assets/images/property-kitchen-dining.jpg",
      description: "Beachfront acre in Diani. Prime development land.",
      agent: "Coastal Properties"
    },
    {
      id: "prop-023",
      title: "1/4 Acre - Runda",
      category: "Land",
      price: 45000000,
      priceType: "sale",
      location: "Runda, Nairobi",
      bedrooms: 0,
      bathrooms: 0,
      featured: true,
      image: "assets/images/property-living-furnished.jpg",
      description: "Prime 1/4 acre in Runda. Gated community, title ready.",
      agent: "Prime Property Hub"
    },
    {
      id: "prop-024",
      title: "2 Acres - Nakuru",
      category: "Land",
      price: 8000000,
      priceType: "sale",
      location: "Nakuru",
      bedrooms: 0,
      bathrooms: 0,
      featured: false,
      image: "assets/images/table-nesting-black-glass-1.jpg",
      description: "2 acres near Nakuru town. Mixed use potential.",
      agent: "Rift Valley Real Estate"
    },
    {
      id: "prop-025",
      title: "50x100 - Juja",
      category: "Land",
      price: 1800000,
      priceType: "sale",
      location: "Juja, Kiambu",
      bedrooms: 0,
      bathrooms: 0,
      featured: false,
      image: "assets/images/table-nesting-black-glass-2.jpg",
      description: "50x100 plot in Juja. Near JKUAT, ready title.",
      agent: "County Properties"
    },
    {
      id: "prop-026",
      title: "10 Acres - Laikipia",
      category: "Land",
      price: 50000000,
      priceType: "sale",
      location: "Laikipia",
      bedrooms: 0,
      bathrooms: 0,
      featured: false,
      image: "assets/images/sofa-cream-set-marble.jpg",
      description: "10 acres in Laikipia. Wildlife area, conservancy.",
      agent: "Highland Properties"
    },

    // HOUSES FOR SALE (8 items)
    {
      id: "prop-027",
      title: "4-Bedroom House - Karen",
      category: "Houses for Sale",
      price: 85000000,
      priceType: "sale",
      location: "Karen, Nairobi",
      bedrooms: 4,
      bathrooms: 4,
      featured: true,
      image: "assets/images/property-luxury-villa.jpg",
      description: "Luxury 4-bedroom house in Karen. Swimming pool, garden, staff quarters.",
      agent: "Prime Property Hub"
    },
    {
      id: "prop-028",
      title: "5-Bedroom Maisonette - Lavington",
      category: "Houses for Sale",
      price: 65000000,
      priceType: "sale",
      location: "Lavington, Nairobi",
      bedrooms: 5,
      bathrooms: 5,
      featured: true,
      image: "assets/images/bed-dark-wood-ottomans.jpg",
      description: "5-bedroom maisonette in Lavington. Modern design, DSQ, parking.",
      agent: "Elite Real Estate"
    },
    {
      id: "prop-029",
      title: "3-Bedroom Bungalow - Ruiru",
      category: "Houses for Sale",
      price: 12000000,
      priceType: "sale",
      location: "Ruiru, Kiambu",
      bedrooms: 3,
      bathrooms: 2,
      featured: false,
      image: "assets/images/bedroom-staging-modern-2.jpg",
      description: "3-bedroom bungalow in Ruiru. On 1/8 acre, gated.",
      agent: "County Properties"
    },
    {
      id: "prop-030",
      title: "6-Bedroom Villa - Muthaiga",
      category: "Houses for Sale",
      price: 150000000,
      priceType: "sale",
      location: "Muthaiga, Nairobi",
      bedrooms: 6,
      bathrooms: 6,
      featured: true,
      image: "assets/images/bed-dark-headboard-blue.jpg",
      description: "Executive 6-bedroom villa in Muthaiga. Pool, tennis court.",
      agent: "Prime Property Hub"
    },
    {
      id: "prop-031",
      title: "4-Bedroom House - Nyali",
      category: "Houses for Sale",
      price: 45000000,
      priceType: "sale",
      location: "Nyali, Mombasa",
      bedrooms: 4,
      bathrooms: 3,
      featured: false,
      image: "assets/images/bathroom-grey-modern.jpg",
      description: "4-bedroom house in Nyali. Beach access, swimming pool.",
      agent: "Coastal Properties"
    },
    {
      id: "prop-032",
      title: "3-Bedroom House - Kisumu",
      category: "Houses for Sale",
      price: 15000000,
      priceType: "sale",
      location: "Milimani, Kisumu",
      bedrooms: 3,
      bathrooms: 2,
      featured: false,
      image: "assets/images/table-coffee-round-wood.jpg",
      description: "3-bedroom house in Milimani. Lake view, modern finish.",
      agent: "Lake Region Properties"
    },
    {
      id: "prop-033",
      title: "5-Bedroom House - Nakuru",
      category: "Houses for Sale",
      price: 25000000,
      priceType: "sale",
      location: "Nakuru",
      bedrooms: 5,
      bathrooms: 4,
      featured: false,
      image: "assets/images/bed-dark-wood-suite-1.jpg",
      description: "5-bedroom house in Nakuru. On 1/4 acre, garden.",
      agent: "Rift Valley Real Estate"
    },
    {
      id: "prop-034",
      title: "4-Bedroom House - Eldoret",
      category: "Houses for Sale",
      price: 18000000,
      priceType: "sale",
      location: "Eldoret",
      bedrooms: 4,
      bathrooms: 3,
      featured: false,
      image: "assets/images/bed-burgundy-velvet-headboard.jpg",
      description: "4-bedroom house in Eldoret. Modern, secure compound.",
      agent: "Highland Properties"
    },

    // RENTALS (8 items)
    {
      id: "prop-035",
      title: "4-Bedroom House for Rent - Karen",
      category: "Rentals",
      price: 250000,
      priceType: "rent",
      location: "Karen, Nairobi",
      bedrooms: 4,
      bathrooms: 4,
      featured: true,
      image: "assets/images/bed-brown-panel-headboard.jpg",
      description: "4-bedroom house for rent in Karen. DSQ, garden, security.",
      agent: "Prime Property Hub"
    },
    {
      id: "prop-036",
      title: "3-Bedroom Maisonette for Rent - Kilimani",
      category: "Rentals",
      price: 150000,
      priceType: "rent",
      location: "Kilimani, Nairobi",
      bedrooms: 3,
      bathrooms: 3,
      featured: false,
      image: "assets/images/bed-grey-geometric-headboard.jpg",
      description: "3-bedroom maisonette for rent. Modern, parking, backup power.",
      agent: "Elite Real Estate"
    },
    {
      id: "prop-037",
      title: "5-Bedroom House for Rent - Muthaiga",
      category: "Rentals",
      price: 400000,
      priceType: "rent",
      location: "Muthaiga, Nairobi",
      bedrooms: 5,
      bathrooms: 5,
      featured: true,
      image: "assets/images/bed-grey-stripe-teal-bench.jpg",
      description: "Executive house for rent. Pool, staff quarters, security.",
      agent: "Prime Property Hub"
    },
    {
      id: "prop-038",
      title: "2-Bedroom Cottage for Rent - Nakuru",
      category: "Rentals",
      price: 35000,
      priceType: "rent",
      location: "Nakuru",
      bedrooms: 2,
      bathrooms: 1,
      featured: false,
      image: "assets/images/tv-unit-white-gold-handles.jpg",
      description: "2-bedroom cottage for rent. Quiet area, garden.",
      agent: "Rift Valley Real Estate"
    },
    {
      id: "prop-039",
      title: "4-Bedroom House for Rent - Nyali",
      category: "Rentals",
      price: 120000,
      priceType: "rent",
      location: "Nyali, Mombasa",
      bedrooms: 4,
      bathrooms: 3,
      featured: false,
      image: "assets/images/tv-unit-white-oak.jpg",
      description: "4-bedroom house for rent in Nyali. Beach access, pool.",
      agent: "Coastal Properties"
    },
    {
      id: "prop-040",
      title: "3-Bedroom House for Rent - Kisumu",
      category: "Rentals",
      price: 45000,
      priceType: "rent",
      location: "Milimani, Kisumu",
      bedrooms: 3,
      bathrooms: 2,
      featured: false,
      image: "assets/images/sofa-grey-sectional-luxury.jpg",
      description: "3-bedroom house for rent. Lake view, modern finish.",
      agent: "Lake Region Properties"
    },
    {
      id: "prop-041",
      title: "6-Bedroom House for Rent - Runda",
      category: "Rentals",
      price: 350000,
      priceType: "rent",
      location: "Runda, Nairobi",
      bedrooms: 6,
      bathrooms: 6,
      featured: false,
      image: "assets/images/sofa-gold-set-curtains.jpg",
      description: "6-bedroom house for rent in Runda. Gated, amenities.",
      agent: "Prime Property Hub"
    },
    {
      id: "prop-042",
      title: "2-Bedroom House for Rent - Eldoret",
      category: "Rentals",
      price: 30000,
      priceType: "rent",
      location: "Eldoret",
      bedrooms: 2,
      bathrooms: 1,
      featured: false,
      image: "assets/images/sofa-grey-u-shaped-teal.jpg",
      description: "2-bedroom house for rent. Secure compound, parking.",
      agent: "Highland Properties"
    },

    // COMMERCIAL PROPERTY (6 items)
    {
      id: "prop-043",
      title: "Office Space - Westlands 2000 sqft",
      category: "Commercial Property",
      price: 150,
      priceType: "per sqft",
      location: "Westlands, Nairobi",
      bedrooms: 0,
      bathrooms: 2,
      featured: true,
      image: "assets/images/sofa-cream-sectional-set.jpg",
      description: "2000 sqft office space in Westlands. Modern building, parking.",
      agent: "Commercial Properties Kenya"
    },
    {
      id: "prop-044",
      title: "Retail Space - Kilimani 500 sqft",
      category: "Commercial Property",
      price: 200,
      priceType: "per sqft",
      location: "Kilimani, Nairobi",
      bedrooms: 0,
      bathrooms: 1,
      featured: false,
      image: "assets/images/sofa-living-room-patterned.jpg",
      description: "500 sqft retail space. High foot traffic area.",
      agent: "Commercial Properties Kenya"
    },
    {
      id: "prop-045",
      title: "Warehouse - Industrial Area 5000 sqft",
      category: "Commercial Property",
      price: 50,
      priceType: "per sqft",
      location: "Industrial Area, Nairobi",
      bedrooms: 0,
      bathrooms: 2,
      featured: false,
      image: "assets/images/table-coffee-hardwood-1.jpg",
      description: "5000 sqft warehouse. Loading bay, high ceiling.",
      agent: "Commercial Properties Kenya"
    },
    {
      id: "prop-046",
      title: "Restaurant Space - Mombasa 1500 sqft",
      category: "Commercial Property",
      price: 120,
      priceType: "per sqft",
      location: "Mombasa",
      bedrooms: 0,
      bathrooms: 2,
      featured: false,
      image: "assets/images/table-coffee-hardwood-2.jpg",
      description: "1500 sqft restaurant space. Kitchen included, beach view.",
      agent: "Coastal Properties"
    },
    {
      id: "prop-047",
      title: "Showroom - Thika Road 3000 sqft",
      category: "Commercial Property",
      price: 80,
      priceType: "per sqft",
      location: "Thika Road",
      bedrooms: 0,
      bathrooms: 2,
      featured: true,
      image: "assets/images/2.jpg",
      description: "3000 sqft showroom. Frontage road, parking.",
      agent: "Commercial Properties Kenya"
    },
    {
      id: "prop-048",
      title: "Office Building - Kisumu 10,000 sqft",
      category: "Commercial Property",
      price: 45000000,
      priceType: "sale",
      location: "Kisumu",
      bedrooms: 0,
      bathrooms: 10,
      featured: false,
      image: "assets/images/bedroom-staging-modern-1.jpg",
      description: "10,000 sqft office building. Multi-tenant, elevator.",
      agent: "Lake Region Properties"
    },

    // OFFICE SPACE (4 items)
    {
      id: "prop-049",
      title: "Co-Working Space - Upper Hill",
      category: "Office Space",
      price: 25000,
      priceType: "per month",
      location: "Upper Hill, Nairobi",
      bedrooms: 0,
      bathrooms: 2,
      featured: true,
      image: "assets/images/sofa-cream-bubble-wood-table.jpg",
      description: "Co-working desk in Upper Hill. High-speed internet, meeting rooms.",
      agent: "Office Solutions Kenya"
    },
    {
      id: "prop-050",
      title: "Private Office - Westlands 200 sqft",
      category: "Office Space",
      price: 45000,
      priceType: "per month",
      location: "Westlands, Nairobi",
      bedrooms: 0,
      bathrooms: 1,
      featured: false,
      image: "assets/images/sofa-brown-l-shaped-ottoman.jpg",
      description: "Private office 200 sqft. Furnished, reception services.",
      agent: "Office Solutions Kenya"
    },
    {
      id: "prop-051",
      title: "Executive Suite - Karen 500 sqft",
      category: "Office Space",
      price: 85000,
      priceType: "per month",
      location: "Karen, Nairobi",
      bedrooms: 0,
      bathrooms: 1,
      featured: false,
      image: "assets/images/sofa-grey-l-shaped-teal.jpg",
      description: "Executive suite 500 sqft. Premium finish, parking.",
      agent: "Office Solutions Kenya"
    },
    {
      id: "prop-052",
      title: "Open Plan Office - Nakuru 1000 sqft",
      category: "Office Space",
      price: 35000,
      priceType: "per month",
      location: "Nakuru",
      bedrooms: 0,
      bathrooms: 2,
      featured: false,
      image: "assets/images/sofa-teal-velvet-set.jpg",
      description: "Open plan office 1000 sqft. Affordable, secure.",
      agent: "Rift Valley Real Estate"
    },

    // STUDENT HOUSING (4 items)
    {
      id: "prop-053",
      title: "Student Hostel - Juja",
      category: "Student Housing",
      price: 12000,
      priceType: "per month",
      location: "Juja, Kiambu",
      bedrooms: 1,
      bathrooms: 1,
      featured: true,
      image: "assets/images/living-room-modern-orange.jpg",
      description: "Student hostel near JKUAT. Single room, WiFi, security.",
      agent: "Student Housing Kenya"
    },
    {
      id: "prop-054",
      title: "Student Apartment - KU",
      category: "Student Housing",
      price: 15000,
      priceType: "per month",
      location: "Kahawa, Nairobi",
      bedrooms: 2,
      bathrooms: 1,
      featured: false,
      image: "assets/images/living-room-beige-cozy.jpg",
      description: "2-bedroom student apartment near KU. Shared, furnished.",
      agent: "Student Housing Kenya"
    },
    {
      id: "prop-055",
      title: "Student Hostel - Eldoret",
      category: "Student Housing",
      price: 10000,
      priceType: "per month",
      location: "Eldoret",
      bedrooms: 1,
      bathrooms: 1,
      featured: false,
      image: "assets/images/property-kitchen-dining.jpg",
      description: "Student hostel in Eldoret. Near university, meals included.",
      agent: "Highland Properties"
    },
    {
      id: "prop-056",
      title: "Student House - Kisumu",
      category: "Student Housing",
      price: 18000,
      priceType: "per month",
      location: "Kisumu",
      bedrooms: 3,
      bathrooms: 1,
      featured: false,
      image: "assets/images/property-living-furnished.jpg",
      description: "3-bedroom student house. Shared, near campus.",
      agent: "Lake Region Properties"
    },

    // LUXURY HOMES (4 items)
    {
      id: "prop-057",
      title: "Luxury Mansion - Muthaiga",
      category: "Luxury Homes",
      price: 350000000,
      priceType: "sale",
      location: "Muthaiga, Nairobi",
      bedrooms: 8,
      bathrooms: 8,
      featured: true,
      image: "assets/images/table-nesting-black-glass-1.jpg",
      description: "8-bedroom luxury mansion. Cinema, gym, pool, tennis court.",
      agent: "Prime Property Hub"
    },
    {
      id: "prop-058",
      title: "Beach Villa - Diani",
      category: "Luxury Homes",
      price: 180000000,
      priceType: "sale",
      location: "Diani, Mombasa",
      bedrooms: 6,
      bathrooms: 6,
      featured: true,
      image: "assets/images/table-nesting-black-glass-2.jpg",
      description: "6-bedroom beach villa. Private beach, infinity pool.",
      agent: "Coastal Properties"
    },
    {
      id: "prop-059",
      title: "Country Estate - Nanyuki",
      category: "Luxury Homes",
      price: 250000000,
      priceType: "sale",
      location: "Nanyuki",
      bedrooms: 7,
      bathrooms: 7,
      featured: false,
      image: "assets/images/sofa-cream-set-marble.jpg",
      description: "7-bedroom country estate. 50 acres, stables, views.",
      agent: "Highland Properties"
    },
    {
      id: "prop-060",
      title: "Penthouse - Westlands",
      category: "Luxury Homes",
      price: 120000000,
      priceType: "sale",
      location: "Westlands, Nairobi",
      bedrooms: 5,
      bathrooms: 5,
      featured: false,
      image: "assets/images/property-luxury-villa.jpg",
      description: "5-bedroom penthouse. 360° views, rooftop terrace.",
      agent: "Elite Real Estate"
    }
  ],

  // Categories for filtering
  categories: [
    "Apartments",
    "Airbnb Units",
    "Land",
    "Houses for Sale",
    "Rentals",
    "Commercial Property",
    "Office Space",
    "Student Housing",
    "Luxury Homes"
  ],

  // Locations for filtering
  locations: [
    "Nairobi",
    "Westlands",
    "Karen",
    "Kilimani",
    "Mombasa",
    "Kisumu",
    "Nakuru",
    "Eldoret",
    "Kiambu",
    "Nanyuki",
    "Diani",
    "Naivasha"
  ],

  // Price ranges for filtering
  priceRanges: [
    { min: 0, max: 50000, label: "Under KSh 50,000" },
    { min: 50000, max: 200000, label: "KSh 50,000 - KSh 200,000" },
    { min: 200000, max: 1000000, label: "KSh 200,000 - KSh 1M" },
    { min: 1000000, max: 999999999, label: "KSh 1M+" }
  ]
};
