/**
 * FURNOSTYLES — SECONDHAND MARKETPLACE DEMO DATA
 * =============================================
 * File: shared/demo-data/secondhand-demo.js
 * Purpose: Demo secondhand products for marketplace testing
 * 
 * This is TEST/DUMMY data for demonstration purposes only.
 * No real payments, no real users, no real transactions.
 */

window.FurnostylesSecondhandDemo = {
  products: [
    // USED SOFAS (15 items)
    {
      id: "sh-001",
      title: "Used 3-Seater Sofa - Grey Fabric",
      category: "Used Sofas",
      price: 25000,
      location: "Nairobi",
      condition: "Good",
      featured: true,
      image: "assets/images/bed-burgundy-velvet-headboard.jpg",
      description: "Well-maintained 3-seater sofa. Minor wear, comfortable.",
      seller: "Private Seller - Karen"
    },
    {
      id: "sh-002",
      title: "Used L-Shaped Sofa - Brown Leather",
      category: "Used Sofas",
      price: 45000,
      location: "Westlands",
      condition: "Good",
      featured: true,
      image: "assets/images/bed-brown-panel-headboard.jpg",
      description: "Brown leather L-shaped sofa. Some scratches, still comfortable.",
      seller: "Private Seller - Westlands"
    },
    {
      id: "sh-003",
      title: "Used Sofa Bed - Beige",
      category: "Used Sofas",
      price: 20000,
      location: "Kisumu",
      condition: "Fair",
      featured: false,
      image: "assets/images/bed-grey-geometric-headboard.jpg",
      description: "Convertible sofa bed. Needs cleaning, functional.",
      seller: "Private Seller - Kisumu"
    },
    {
      id: "sh-004",
      title: "Used 2-Seater Love Seat - Blue",
      category: "Used Sofas",
      price: 15000,
      location: "Mombasa",
      condition: "Good",
      featured: false,
      image: "assets/images/bed-grey-stripe-teal-bench.jpg",
      description: "Compact 2-seater in blue. Great condition.",
      seller: "Private Seller - Mombasa"
    },
    {
      id: "sh-005",
      title: "Used Recliner Sofa - Black",
      category: "Used Sofas",
      price: 35000,
      location: "Nairobi",
      condition: "Fair",
      featured: false,
      image: "assets/images/tv-unit-white-gold-handles.jpg",
      description: "Black recliner sofa. Motor works, some wear on fabric.",
      seller: "Private Seller - Nairobi"
    },
    {
      id: "sh-006",
      title: "Used Corner Sofa - Grey",
      category: "Used Sofas",
      price: 40000,
      location: "Nakuru",
      condition: "Good",
      featured: true,
      image: "assets/images/tv-unit-white-oak.jpg",
      description: "Grey corner sofa. Clean, minor fading.",
      seller: "Private Seller - Nakuru"
    },
    {
      id: "sh-007",
      title: "Used Chesterfield - Vintage",
      category: "Used Sofas",
      price: 55000,
      location: "Karen",
      condition: "Fair",
      featured: false,
      image: "assets/images/sofa-grey-sectional-luxury.jpg",
      description: "Vintage Chesterfield. Leather worn, character piece.",
      seller: "Antique Collector"
    },
    {
      id: "sh-008",
      title: "Used Sectional - Beige",
      category: "Used Sofas",
      price: 30000,
      location: "Eldoret",
      condition: "Good",
      featured: false,
      image: "assets/images/sofa-gold-set-curtains.jpg",
      description: "Beige sectional sofa. Removable covers.",
      seller: "Private Seller - Eldoret"
    },
    {
      id: "sh-009",
      title: "Used Armchair - Brown",
      category: "Used Sofas",
      price: 8000,
      location: "Kiambu",
      condition: "Good",
      featured: false,
      image: "assets/images/sofa-grey-u-shaped-teal.jpg",
      description: "Single brown armchair. Sturdy frame.",
      seller: "Private Seller - Kiambu"
    },
    {
      id: "sh-010",
      title: "Used Velvet Sofa - Green",
      category: "Used Sofas",
      price: 28000,
      location: "Nairobi",
      condition: "Fair",
      featured: false,
      image: "assets/images/sofa-cream-sectional-set.jpg",
      description: "Green velvet sofa. Some stains, still presentable.",
      seller: "Private Seller - Nairobi"
    },
    {
      id: "sh-011",
      title: "Used Futon - Black Frame",
      category: "Used Sofas",
      price: 12000,
      location: "Westlands",
      condition: "Good",
      featured: false,
      image: "assets/images/sofa-living-room-patterned.jpg",
      description: "Black metal futon. Mattress included.",
      seller: "Student Moving Sale"
    },
    {
      id: "sh-012",
      title: "Used Loveseat - Floral",
      category: "Used Sofas",
      price: 10000,
      location: "Kisumu",
      condition: "Fair",
      featured: false,
      image: "assets/images/table-coffee-hardwood-1.jpg",
      description: "Floral pattern loveseat. Vintage style.",
      seller: "Private Seller - Kisumu"
    },
    {
      id: "sh-013",
      title: "Used Chaise - Cream",
      category: "Used Sofas",
      price: 15000,
      location: "Mombasa",
      condition: "Good",
      featured: false,
      image: "assets/images/table-coffee-hardwood-2.jpg",
      description: "Cream chaise lounge. Minor wear.",
      seller: "Private Seller - Mombasa"
    },
    {
      id: "sh-014",
      title: "Used Sofa Set - 3+1",
      category: "Used Sofas",
      price: 35000,
      location: "Nakuru",
      condition: "Fair",
      featured: false,
      image: "assets/images/2.jpg",
      description: "3-seater and armchair set. Needs cleaning.",
      seller: "Private Seller - Nakuru"
    },
    {
      id: "sh-015",
      title: "Used Patio Sofa - Rattan",
      category: "Used Sofas",
      price: 20000,
      location: "Eldoret",
      condition: "Fair",
      featured: false,
      image: "assets/images/bedroom-staging-modern-1.jpg",
      description: "Rattan patio sofa. Weathered but functional.",
      seller: "Garden Sale"
    },

    // USED OFFICE FURNITURE (12 items)
    {
      id: "sh-016",
      title: "Used Office Desk - Large",
      category: "Used Office Furniture",
      price: 15000,
      location: "Nairobi",
      condition: "Good",
      featured: true,
      image: "assets/images/sofa-cream-bubble-wood-table.jpg",
      description: "Large office desk with drawers. Solid wood.",
      seller: "Office Closing Sale"
    },
    {
      id: "sh-017",
      title: "Used Office Chair - Ergonomic",
      category: "Used Office Furniture",
      price: 8000,
      location: "Westlands",
      condition: "Good",
      featured: false,
      image: "assets/images/sofa-brown-l-shaped-ottoman.jpg",
      description: "Ergonomic office chair. Adjustable height.",
      seller: "Private Seller - Westlands"
    },
    {
      id: "sh-018",
      title: "Used Filing Cabinet - 4 Drawer",
      category: "Used Office Furniture",
      price: 10000,
      location: "Karen",
      condition: "Good",
      featured: false,
      image: "assets/images/sofa-grey-l-shaped-teal.jpg",
      description: "4-drawer filing cabinet. Locking mechanism works.",
      seller: "Office Liquidation"
    },
    {
      id: "sh-019",
      title: "Used Conference Table - 8 Seater",
      category: "Used Office Furniture",
      price: 35000,
      location: "Kisumu",
      condition: "Fair",
      featured: true,
      image: "assets/images/sofa-teal-velvet-set.jpg",
      description: "Large conference table. Some scratches.",
      seller: "Business Closing Sale"
    },
    {
      id: "sh-020",
      title: "Used Bookshelf - Tall",
      category: "Used Office Furniture",
      price: 12000,
      location: "Mombasa",
      condition: "Good",
      featured: false,
      image: "assets/images/living-room-modern-orange.jpg",
      description: "Tall bookshelf. Adjustable shelves.",
      seller: "Private Seller - Mombasa"
    },
    {
      id: "sh-021",
      title: "Used Reception Desk",
      category: "Used Office Furniture",
      price: 25000,
      location: "Nakuru",
      condition: "Fair",
      featured: false,
      image: "assets/images/living-room-beige-cozy.jpg",
      description: "Modern reception desk. Some wear.",
      seller: "Office Liquidation"
    },
    {
      id: "sh-022",
      title: "Used Standing Desk - Manual",
      category: "Used Office Furniture",
      price: 18000,
      location: "Eldoret",
      condition: "Good",
      featured: false,
      image: "assets/images/property-kitchen-dining.jpg",
      description: "Manual standing desk. Crank mechanism works.",
      seller: "Private Seller - Eldoret"
    },
    {
      id: "sh-023",
      title: "Used Office Chair Set - 5",
      category: "Used Office Furniture",
      price: 25000,
      location: "Kiambu",
      condition: "Fair",
      featured: true,
      image: "assets/images/property-living-furnished.jpg",
      description: "Set of 5 office chairs. Mixed condition.",
      seller: "Office Closing Sale"
    },
    {
      id: "sh-024",
      title: "Used Whiteboard - 4x6ft",
      category: "Used Office Furniture",
      price: 5000,
      location: "Nairobi",
      condition: "Good",
      featured: false,
      image: "assets/images/table-nesting-black-glass-1.jpg",
      description: "Large whiteboard. Clean surface.",
      seller: "Private Seller - Nairobi"
    },
    {
      id: "sh-025",
      title: "Used Printer Cabinet",
      category: "Used Office Furniture",
      price: 8000,
      location: "Westlands",
      condition: "Good",
      featured: false,
      image: "assets/images/table-nesting-black-glass-2.jpg",
      description: "Printer storage cabinet. Rolling wheels.",
      seller: "Office Liquidation"
    },
    {
      id: "sh-026",
      title: "Used Partition Walls - Set",
      category: "Used Office Furniture",
      price: 20000,
      location: "Karen",
      condition: "Fair",
      featured: false,
      image: "assets/images/sofa-cream-set-marble.jpg",
      description: "Set of partition walls. Some panels damaged.",
      seller: "Business Closing Sale"
    },
    {
      id: "sh-027",
      title: "Used Laptop Stand - Adjustable",
      category: "Used Office Furniture",
      price: 3000,
      location: "Kisumu",
      condition: "Good",
      featured: false,
      image: "assets/images/property-luxury-villa.jpg",
      description: "Adjustable laptop stand. Good condition.",
      seller: "Private Seller - Kisumu"
    },

    // USED ELECTRONICS (12 items)
    {
      id: "sh-028",
      title: "Used TV - 43 inch Smart",
      category: "Used Electronics",
      price: 25000,
      location: "Nairobi",
      condition: "Good",
      featured: true,
      image: "assets/images/bed-dark-wood-ottomans.jpg",
      description: "43 inch Smart TV. Works perfectly, remote included.",
      seller: "Private Seller - Nairobi"
    },
    {
      id: "sh-029",
      title: "Used Microwave - 25L",
      category: "Used Electronics",
      price: 6000,
      location: "Westlands",
      condition: "Good",
      featured: false,
      image: "assets/images/bedroom-staging-modern-2.jpg",
      description: "25L microwave oven. Clean interior.",
      seller: "Private Seller - Westlands"
    },
    {
      id: "sh-030",
      title: "Used Refrigerator - 250L",
      category: "Used Electronics",
      price: 35000,
      location: "Karen",
      condition: "Fair",
      featured: true,
      image: "assets/images/bed-dark-headboard-blue.jpg",
      description: "250L refrigerator. Some dents, cooling works.",
      seller: "Private Seller - Karen"
    },
    {
      id: "sh-031",
      title: "Used Washing Machine - 7kg",
      category: "Used Electronics",
      price: 20000,
      location: "Kisumu",
      condition: "Good",
      featured: false,
      image: "assets/images/bathroom-grey-modern.jpg",
      description: "7kg washing machine. Front loader.",
      seller: "Private Seller - Kisumu"
    },
    {
      id: "sh-032",
      title: "Used Blender - 1.5L",
      category: "Used Electronics",
      price: 2500,
      location: "Mombasa",
      condition: "Good",
      featured: false,
      image: "assets/images/table-coffee-round-wood.jpg",
      description: "1.5L blender. Works well.",
      seller: "Private Seller - Mombasa"
    },
    {
      id: "sh-033",
      title: "Used Rice Cooker - 5L",
      category: "Used Electronics",
      price: 3000,
      location: "Nakuru",
      condition: "Good",
      featured: false,
      image: "assets/images/bed-dark-wood-suite-1.jpg",
      description: "5L rice cooker. Non-stick pot.",
      seller: "Private Seller - Nakuru"
    },
    {
      id: "sh-034",
      title: "Used Iron - Steam",
      category: "Used Electronics",
      price: 1500,
      location: "Eldoret",
      condition: "Fair",
      featured: false,
      image: "assets/images/bed-burgundy-velvet-headboard.jpg",
      description: "Steam iron. Some mineral buildup.",
      seller: "Private Seller - Eldoret"
    },
    {
      id: "sh-035",
      title: "Used Fan - Standing",
      category: "Used Electronics",
      price: 3500,
      location: "Kiambu",
      condition: "Good",
      featured: false,
      image: "assets/images/bed-brown-panel-headboard.jpg",
      description: "Standing fan. 3 speed settings.",
      seller: "Private Seller - Kiambu"
    },
    {
      id: "sh-036",
      title: "Used Heater - Electric",
      category: "Used Electronics",
      price: 4000,
      location: "Nairobi",
      condition: "Good",
      featured: false,
      image: "assets/images/bed-grey-geometric-headboard.jpg",
      description: "Electric heater. Thermostat works.",
      seller: "Private Seller - Nairobi"
    },
    {
      id: "sh-037",
      title: "Used Coffee Maker - Drip",
      category: "Used Electronics",
      price: 4500,
      location: "Westlands",
      condition: "Fair",
      featured: false,
      image: "assets/images/bed-grey-stripe-teal-bench.jpg",
      description: "Drip coffee maker. Needs descaling.",
      seller: "Private Seller - Westlands"
    },
    {
      id: "sh-038",
      title: "Used Toaster - 2 Slice",
      category: "Used Electronics",
      price: 1500,
      location: "Karen",
      condition: "Good",
      featured: false,
      image: "assets/images/tv-unit-white-gold-handles.jpg",
      description: "2-slice toaster. Crumb tray works.",
      seller: "Private Seller - Karen"
    },
    {
      id: "sh-039",
      title: "Used Air Fryer - 3.5L",
      category: "Used Electronics",
      price: 8000,
      location: "Kisumu",
      condition: "Good",
      featured: false,
      image: "assets/images/tv-unit-white-oak.jpg",
      description: "3.5L air fryer. Like new.",
      seller: "Private Seller - Kisumu"
    },

    // USED TOOLS (10 items)
    {
      id: "sh-040",
      title: "Used Drill - Cordless 18V",
      category: "Used Tools",
      price: 8000,
      location: "Nairobi",
      condition: "Good",
      featured: true,
      image: "assets/images/sofa-grey-sectional-luxury.jpg",
      description: "18V cordless drill. Battery holds charge.",
      seller: "DIY Enthusiast"
    },
    {
      id: "sh-041",
      title: "Used Circular Saw - 7 inch",
      category: "Used Tools",
      price: 10000,
      location: "Westlands",
      condition: "Fair",
      featured: false,
      image: "assets/images/sofa-gold-set-curtains.jpg",
      description: "7 inch circular saw. Blade needs replacement.",
      seller: "Contractor Sale"
    },
    {
      id: "sh-042",
      title: "Used Tool Set - 50 pieces",
      category: "Used Tools",
      price: 15000,
      location: "Karen",
      condition: "Good",
      featured: true,
      image: "assets/images/sofa-grey-u-shaped-teal.jpg",
      description: "50-piece tool set. Some tools missing.",
      seller: "Private Seller - Karen"
    },
    {
      id: "sh-043",
      title: "Used Ladder - Aluminum 6ft",
      category: "Used Tools",
      price: 5000,
      location: "Kisumu",
      condition: "Good",
      featured: false,
      image: "assets/images/sofa-cream-sectional-set.jpg",
      description: "6ft aluminum ladder. Sturdy.",
      seller: "Private Seller - Kisumu"
    },
    {
      id: "sh-044",
      title: "Used Hammer Drill - SDS",
      category: "Used Tools",
      price: 12000,
      location: "Mombasa",
      condition: "Fair",
      featured: false,
      image: "assets/images/sofa-living-room-patterned.jpg",
      description: "SDS hammer drill. Heavy use.",
      seller: "Contractor Sale"
    },
    {
      id: "sh-045",
      title: "Used Jigsaw - 500W",
      category: "Used Tools",
      price: 6000,
      location: "Nakuru",
      condition: "Good",
      featured: false,
      image: "assets/images/table-coffee-hardwood-1.jpg",
      description: "500W jigsaw. Works well.",
      seller: "Private Seller - Nakuru"
    },
    {
      id: "sh-046",
      title: "Used Tool Box - Large",
      category: "Used Tools",
      price: 3000,
      location: "Eldoret",
      condition: "Fair",
      featured: false,
      image: "assets/images/table-coffee-hardwood-2.jpg",
      description: "Large tool box. Some rust.",
      seller: "Garage Sale"
    },
    {
      id: "sh-047",
      title: "Used Angle Grinder - 1000W",
      category: "Used Tools",
      price: 4500,
      location: "Kiambu",
      condition: "Good",
      featured: false,
      image: "assets/images/2.jpg",
      description: "1000W angle grinder. Good condition.",
      seller: "Private Seller - Kiambu"
    },
    {
      id: "sh-048",
      title: "Used Level - 1200mm",
      category: "Used Tools",
      price: 1500,
      location: "Nairobi",
      condition: "Good",
      featured: false,
      image: "assets/images/bedroom-staging-modern-1.jpg",
      description: "1200mm spirit level. Accurate.",
      seller: "DIY Enthusiast"
    },
    {
      id: "sh-049",
      title: "Used Sawhorse Set - 2",
      category: "Used Tools",
      price: 3500,
      location: "Westlands",
      condition: "Good",
      featured: false,
      image: "assets/images/sofa-cream-bubble-wood-table.jpg",
      description: "Set of 2 sawhorses. Sturdy.",
      seller: "Contractor Sale"
    },

    // USED BEDS (10 items)
    {
      id: "sh-050",
      title: "Used King Bed Frame - Wood",
      category: "Used Beds",
      price: 25000,
      location: "Nairobi",
      condition: "Good",
      featured: true,
      image: "assets/images/sofa-brown-l-shaped-ottoman.jpg",
      description: "King size wooden bed frame. Solid construction.",
      seller: "Private Seller - Nairobi"
    },
    {
      id: "sh-051",
      title: "Used Queen Mattress - Memory Foam",
      category: "Used Beds",
      price: 15000,
      location: "Karen",
      condition: "Fair",
      featured: false,
      image: "assets/images/sofa-grey-l-shaped-teal.jpg",
      description: "Queen memory foam mattress. Some indentations.",
      seller: "Private Seller - Karen"
    },
    {
      id: "sh-052",
      title: "Used Single Bed - Metal",
      category: "Used Beds",
      price: 8000,
      location: "Kisumu",
      condition: "Good",
      featured: false,
      image: "assets/images/sofa-teal-velvet-set.jpg",
      description: "Single metal bed frame. Includes mattress.",
      seller: "Student Moving Sale"
    },
    {
      id: "sh-053",
      title: "Used Bunk Bed - Wood",
      category: "Used Beds",
      price: 18000,
      location: "Mombasa",
      condition: "Fair",
      featured: false,
      image: "assets/images/living-room-modern-orange.jpg",
      description: "Wooden bunk bed. Some scratches.",
      seller: "Family Sale"
    },
    {
      id: "sh-054",
      title: "Used Day Bed - With Trundle",
      category: "Used Beds",
      price: 20000,
      location: "Nakuru",
      condition: "Good",
      featured: true,
      image: "assets/images/living-room-beige-cozy.jpg",
      description: "Day bed with trundle. Great for guests.",
      seller: "Private Seller - Nakuru"
    },
    {
      id: "sh-055",
      title: "Used Double Mattress - Spring",
      category: "Used Beds",
      price: 10000,
      location: "Eldoret",
      condition: "Fair",
      featured: false,
      image: "assets/images/property-kitchen-dining.jpg",
      description: "Double spring mattress. Medium firm.",
      seller: "Private Seller - Eldoret"
    },
    {
      id: "sh-056",
      title: "Used Bed Frame - Platform",
      category: "Used Beds",
      price: 12000,
      location: "Kiambu",
      condition: "Good",
      featured: false,
      image: "assets/images/property-living-furnished.jpg",
      description: "Platform bed frame. No mattress included.",
      seller: "Private Seller - Kiambu"
    },
    {
      id: "sh-057",
      title: "Used Headboard - Upholstered",
      category: "Used Beds",
      price: 8000,
      location: "Nairobi",
      condition: "Good",
      featured: false,
      image: "assets/images/table-nesting-black-glass-1.jpg",
      description: "Upholstered headboard. Grey fabric.",
      seller: "Private Seller - Nairobi"
    },
    {
      id: "sh-058",
      title: "Used Box Spring - Queen",
      category: "Used Beds",
      price: 6000,
      location: "Westlands",
      condition: "Fair",
      featured: false,
      image: "assets/images/table-nesting-black-glass-2.jpg",
      description: "Queen box spring. Some wear.",
      seller: "Private Seller - Westlands"
    },
    {
      id: "sh-059",
      title: "Used Bedside Table Set - 2",
      category: "Used Beds",
      price: 5000,
      location: "Karen",
      condition: "Good",
      featured: false,
      image: "assets/images/sofa-cream-set-marble.jpg",
      description: "Set of 2 bedside tables. Matching.",
      seller: "Private Seller - Karen"
    },

    // USED APPLIANCES (10 items)
    {
      id: "sh-060",
      title: "Used Stove - 4 Burner Gas",
      category: "Used Appliances",
      price: 15000,
      location: "Nairobi",
      condition: "Good",
      featured: true,
      image: "assets/images/property-luxury-villa.jpg",
      description: "4-burner gas stove. All burners work.",
      seller: "Private Seller - Nairobi"
    },
    {
      id: "sh-061",
      title: "Used Oven - Electric",
      category: "Used Appliances",
      price: 20000,
      location: "Westlands",
      condition: "Fair",
      featured: false,
      image: "assets/images/bed-dark-wood-ottomans.jpg",
      description: "Electric oven. Element needs replacement.",
      seller: "Private Seller - Westlands"
    },
    {
      id: "sh-062",
      title: "Used Dishwasher - 12 Place",
      category: "Used Appliances",
      price: 25000,
      location: "Karen",
      condition: "Good",
      featured: false,
      image: "assets/images/bedroom-staging-modern-2.jpg",
      description: "12-place dishwasher. Works well.",
      seller: "Private Seller - Karen"
    },
    {
      id: "sh-063",
      title: "Used Water Dispenser - Hot/Cold",
      category: "Used Appliances",
      price: 8000,
      location: "Kisumu",
      condition: "Good",
      featured: false,
      image: "assets/images/bed-dark-headboard-blue.jpg",
      description: "Hot/cold water dispenser. Clean.",
      seller: "Office Liquidation"
    },
    {
      id: "sh-064",
      title: "Used Vacuum Cleaner - Upright",
      category: "Used Appliances",
      price: 6000,
      location: "Mombasa",
      condition: "Fair",
      featured: false,
      image: "assets/images/bathroom-grey-modern.jpg",
      description: "Upright vacuum. Belt needs replacement.",
      seller: "Private Seller - Mombasa"
    },
    {
      id: "sh-065",
      title: "Used Kettle - Electric 1.7L",
      category: "Used Appliances",
      price: 1500,
      location: "Nakuru",
      condition: "Good",
      featured: false,
      image: "assets/images/table-coffee-round-wood.jpg",
      description: "1.7L electric kettle. Fast boil.",
      seller: "Private Seller - Nakuru"
    },
    {
      id: "sh-066",
      title: "Used Food Processor - 11 Cup",
      category: "Used Appliances",
      price: 7000,
      location: "Eldoret",
      condition: "Good",
      featured: false,
      image: "assets/images/bed-dark-wood-suite-1.jpg",
      description: "11-cup food processor. All attachments.",
      seller: "Private Seller - Eldoret"
    },
    {
      id: "sh-067",
      title: "Used Slow Cooker - 6L",
      category: "Used Appliances",
      price: 3500,
      location: "Kiambu",
      condition: "Good",
      featured: false,
      image: "assets/images/bed-burgundy-velvet-headboard.jpg",
      description: "6L slow cooker. Ceramic pot.",
      seller: "Private Seller - Kiambu"
    },
    {
      id: "sh-068",
      title: "Used Sandwich Maker",
      category: "Used Appliances",
      price: 2000,
      location: "Nairobi",
      condition: "Good",
      featured: false,
      image: "assets/images/bed-brown-panel-headboard.jpg",
      description: "Sandwich maker. Non-stick plates.",
      seller: "Private Seller - Nairobi"
    },
    {
      id: "sh-069",
      title: "Used Juicer - Centrifugal",
      category: "Used Appliances",
      price: 5000,
      location: "Westlands",
      condition: "Fair",
      featured: false,
      image: "assets/images/bed-grey-geometric-headboard.jpg",
      description: "Centrifugal juicer. Needs cleaning.",
      seller: "Private Seller - Westlands"
    },

    // USED BUILDING MATERIALS (10 items)
    {
      id: "sh-070",
      title: "Used Tiles - Ceramic 30x30",
      category: "Used Building Materials",
      price: 300,
      location: "Nairobi",
      condition: "Good",
      featured: true,
      image: "assets/images/bed-grey-stripe-teal-bench.jpg",
      description: "Leftover ceramic tiles. 50 pieces.",
      seller: "Contractor Leftovers"
    },
    {
      id: "sh-071",
      title: "Used Paint - 5L Assorted",
      category: "Used Building Materials",
      price: 2000,
      location: "Karen",
      condition: "Fair",
      featured: false,
      image: "assets/images/tv-unit-white-gold-handles.jpg",
      description: "Assorted leftover paint. Various colors.",
      seller: "DIY Project Leftovers"
    },
    {
      id: "sh-072",
      title: "Used Timber - Pine Offcuts",
      category: "Used Building Materials",
      price: 1500,
      location: "Kisumu",
      condition: "Good",
      featured: false,
      image: "assets/images/tv-unit-white-oak.jpg",
      description: "Pine timber offcuts. Various sizes.",
      seller: "Woodworker Leftovers"
    },
    {
      id: "sh-073",
      title: "Used Bricks - 200 pieces",
      category: "Used Building Materials",
      price: 5000,
      location: "Mombasa",
      condition: "Good",
      featured: false,
      image: "assets/images/sofa-grey-sectional-luxury.jpg",
      description: "200 used bricks. Clean condition.",
      seller: "Demolition Sale"
    },
    {
      id: "sh-074",
      title: "Used Roofing Sheets - 10 pieces",
      category: "Used Building Materials",
      price: 8000,
      location: "Nakuru",
      condition: "Fair",
      featured: false,
      image: "assets/images/sofa-gold-set-curtains.jpg",
      description: "10 used roofing sheets. Some rust.",
      seller: "Renovation Leftovers"
    },
    {
      id: "sh-075",
      title: "Used Gypsum Board - 5 sheets",
      category: "Used Building Materials",
      price: 2500,
      location: "Eldoret",
      condition: "Good",
      featured: false,
      image: "assets/images/sofa-grey-u-shaped-teal.jpg",
      description: "5 used gypsum boards. Cut pieces.",
      seller: "Contractor Leftovers"
    },
    {
      id: "sh-076",
      title: "Used Cement - 5 bags",
      category: "Used Building Materials",
      price: 3000,
      location: "Kiambu",
      condition: "Fair",
      featured: false,
      image: "assets/images/sofa-cream-sectional-set.jpg",
      description: "5 bags of opened cement. Partially used.",
      seller: "DIY Project Leftovers"
    },
    {
      id: "sh-077",
      title: "Used Pipes - PVC Assorted",
      category: "Used Building Materials",
      price: 2000,
      location: "Nairobi",
      condition: "Good",
      featured: false,
      image: "assets/images/sofa-living-room-patterned.jpg",
      description: "Assorted PVC pipes. Various sizes.",
      seller: "Plumber Leftovers"
    },
    {
      id: "sh-078",
      title: "Used Electrical Wire - 50m",
      category: "Used Building Materials",
      price: 3000,
      location: "Westlands",
      condition: "Good",
      featured: false,
      image: "assets/images/table-coffee-hardwood-1.jpg",
      description: "50m electrical wire. Leftover roll.",
      seller: "Electrician Leftovers"
    },
    {
      id: "sh-079",
      title: "Used Insulation - Roll",
      category: "Used Building Materials",
      price: 4000,
      location: "Karen",
      condition: "Fair",
      featured: false,
      image: "assets/images/table-coffee-hardwood-2.jpg",
      description: "Roll of insulation. Partially used.",
      seller: "Contractor Leftovers"
    },

    // USED LIGHTING (8 items)
    {
      id: "sh-080",
      title: "Used Chandelier - 5 Light",
      category: "Used Lighting",
      price: 8000,
      location: "Nairobi",
      condition: "Good",
      featured: true,
      image: "assets/images/2.jpg",
      description: "5-light chandelier. Brass finish.",
      seller: "Private Seller - Nairobi"
    },
    {
      id: "sh-081",
      title: "Used Floor Lamp - Adjustable",
      category: "Used Lighting",
      price: 3500,
      location: "Westlands",
      condition: "Good",
      featured: false,
      image: "assets/images/bedroom-staging-modern-1.jpg",
      description: "Adjustable floor lamp. Chrome finish.",
      seller: "Private Seller - Westlands"
    },
    {
      id: "sh-082",
      title: "Used Table Lamp - Ceramic",
      category: "Used Lighting",
      price: 2000,
      location: "Karen",
      condition: "Fair",
      featured: false,
      image: "assets/images/sofa-cream-bubble-wood-table.jpg",
      description: "Ceramic table lamp. Minor chip.",
      seller: "Private Seller - Karen"
    },
    {
      id: "sh-083",
      title: "Used Pendant Light - Glass",
      category: "Used Lighting",
      price: 2500,
      location: "Kisumu",
      condition: "Good",
      featured: false,
      image: "assets/images/sofa-brown-l-shaped-ottoman.jpg",
      description: "Glass pendant light. Modern style.",
      seller: "Private Seller - Kisumu"
    },
    {
      id: "sh-084",
      title: "Used Wall Sconces - Pair",
      category: "Used Lighting",
      price: 3000,
      location: "Mombasa",
      condition: "Good",
      featured: false,
      image: "assets/images/sofa-grey-l-shaped-teal.jpg",
      description: "Pair of wall sconces. Brass.",
      seller: "Private Seller - Mombasa"
    },
    {
      id: "sh-085",
      title: "Used Outdoor Light - Solar",
      category: "Used Lighting",
      price: 1500,
      location: "Nakuru",
      condition: "Fair",
      featured: false,
      image: "assets/images/sofa-teal-velvet-set.jpg",
      description: "Solar outdoor light. Battery weak.",
      seller: "Garden Sale"
    },
    {
      id: "sh-086",
      title: "Used Ceiling Light - LED Panel",
      category: "Used Lighting",
      price: 4500,
      location: "Eldoret",
      condition: "Good",
      featured: false,
      image: "assets/images/living-room-modern-orange.jpg",
      description: "LED panel ceiling light. 600x600mm.",
      seller: "Office Liquidation"
    },
    {
      id: "sh-087",
      title: "Used Strip Light - LED 5m",
      category: "Used Lighting",
      price: 2000,
      location: "Kiambu",
      condition: "Good",
      featured: false,
      image: "assets/images/living-room-beige-cozy.jpg",
      description: "5m LED strip light. Warm white.",
      seller: "Private Seller - Kiambu"
    },

    // USED WARDROBES (8 items)
    {
      id: "sh-088",
      title: "Used Wardrobe - 3 Door",
      category: "Used Wardrobes",
      price: 15000,
      location: "Nairobi",
      condition: "Good",
      featured: true,
      image: "assets/images/property-kitchen-dining.jpg",
      description: "3-door wardrobe. Mirrored center.",
      seller: "Private Seller - Nairobi"
    },
    {
      id: "sh-089",
      title: "Used Wardrobe - 2 Door",
      category: "Used Wardrobes",
      price: 10000,
      location: "Westlands",
      condition: "Fair",
      featured: false,
      image: "assets/images/property-living-furnished.jpg",
      description: "2-door wardrobe. Some scratches.",
      seller: "Private Seller - Westlands"
    },
    {
      id: "sh-090",
      title: "Used Closet Organizer",
      category: "Used Wardrobes",
      price: 8000,
      location: "Karen",
      condition: "Good",
      featured: false,
      image: "assets/images/table-nesting-black-glass-1.jpg",
      description: "Closet organizer system. Modular.",
      seller: "Private Seller - Karen"
    },
    {
      id: "sh-091",
      title: "Used Open Wardrobe - Metal",
      category: "Used Wardrobes",
      price: 12000,
      location: "Kisumu",
      condition: "Good",
      featured: false,
      image: "assets/images/table-nesting-black-glass-2.jpg",
      description: "Metal open wardrobe. Industrial style.",
      seller: "Private Seller - Kisumu"
    },
    {
      id: "sh-092",
      title: "Used Kids Wardrobe - Colorful",
      category: "Used Wardrobes",
      price: 7000,
      location: "Mombasa",
      condition: "Fair",
      featured: false,
      image: "assets/images/sofa-cream-set-marble.jpg",
      description: "Colorful kids wardrobe. Some stickers.",
      seller: "Family Sale"
    },
    {
      id: "sh-093",
      title: "Used Wardrobe - Sliding Door",
      category: "Used Wardrobes",
      price: 18000,
      location: "Nakuru",
      condition: "Good",
      featured: false,
      image: "assets/images/property-luxury-villa.jpg",
      description: "Sliding door wardrobe. Mirror doors.",
      seller: "Private Seller - Nakuru"
    },
    {
      id: "sh-094",
      title: "Used Chest of Drawers - 5 Drawer",
      category: "Used Wardrobes",
      price: 8000,
      location: "Eldoret",
      condition: "Good",
      featured: false,
      image: "assets/images/bed-dark-wood-ottomans.jpg",
      description: "5-drawer chest. Solid wood.",
      seller: "Private Seller - Eldoret"
    },
    {
      id: "sh-095",
      title: "Used Dresser - With Mirror",
      category: "Used Wardrobes",
      price: 10000,
      location: "Kiambu",
      condition: "Fair",
      featured: false,
      image: "assets/images/bedroom-staging-modern-2.jpg",
      description: "Dresser with mirror. Some wear.",
      seller: "Private Seller - Kiambu"
    },

    // CLEARANCE ITEMS (8 items)
    {
      id: "sh-096",
      title: "Clearance - Mixed Furniture Lot",
      category: "Clearance Items",
      price: 45000,
      location: "Nairobi",
      condition: "Fair",
      featured: true,
      image: "assets/images/bed-dark-headboard-blue.jpg",
      description: "Mixed furniture lot. Must take all.",
      seller: "Store Clearance"
    },
    {
      id: "sh-097",
      title: "Clearance - Kitchen Appliances Bundle",
      category: "Clearance Items",
      price: 35000,
      location: "Westlands",
      condition: "Fair",
      featured: false,
      image: "assets/images/bathroom-grey-modern.jpg",
      description: "Kitchen appliances bundle. As-is.",
      seller: "Store Clearance"
    },
    {
      id: "sh-098",
      title: "Clearance - Office Furniture Set",
      category: "Clearance Items",
      price: 40000,
      location: "Karen",
      condition: "Fair",
      featured: false,
      image: "assets/images/table-coffee-round-wood.jpg",
      description: "Complete office set. Desks and chairs.",
      seller: "Office Liquidation"
    },
    {
      id: "sh-099",
      title: "Clearance - Building Materials Lot",
      category: "Clearance Items",
      price: 25000,
      location: "Kisumu",
      condition: "Fair",
      featured: false,
      image: "assets/images/bed-dark-wood-suite-1.jpg",
      description: "Building materials lot. Various items.",
      seller: "Contractor Clearance"
    },
    {
      id: "sh-100",
      title: "Clearance - Home Decor Bundle",
      category: "Clearance Items",
      price: 15000,
      location: "Mombasa",
      condition: "Fair",
      featured: false,
      image: "assets/images/bed-burgundy-velvet-headboard.jpg",
      description: "Home decor bundle. Curtains, rugs, art.",
      seller: "Store Clearance"
    },
    {
      id: "sh-101",
      title: "Clearance - Bedding Set - King",
      category: "Clearance Items",
      price: 8000,
      location: "Nakuru",
      condition: "Good",
      featured: false,
      image: "assets/images/bed-brown-panel-headboard.jpg",
      description: "King bedding set. Sheets, comforter, pillows.",
      seller: "Hotel Clearance"
    },
    {
      id: "sh-102",
      title: "Clearance - Garden Furniture Set",
      category: "Clearance Items",
      price: 20000,
      location: "Eldoret",
      condition: "Fair",
      featured: false,
      image: "assets/images/bed-grey-geometric-headboard.jpg",
      description: "Garden furniture set. Weathered.",
      seller: "Garden Center Clearance"
    },
    {
      id: "sh-103",
      title: "Clearance - Electronics Bundle",
      category: "Clearance Items",
      price: 30000,
      location: "Kiambu",
      condition: "Fair",
      featured: false,
      image: "assets/images/bed-grey-stripe-teal-bench.jpg",
      description: "Electronics bundle. Various items.",
      seller: "Store Clearance"
    },

    // MISCELLANEOUS (7 items)
    {
      id: "sh-104",
      title: "Used Curtains - Velvet - Pair",
      category: "Miscellaneous",
      price: 5000,
      location: "Nairobi",
      condition: "Good",
      featured: false,
      image: "assets/images/tv-unit-white-gold-handles.jpg",
      description: "Pair of velvet curtains. Burgundy.",
      seller: "Private Seller - Nairobi"
    },
    {
      id: "sh-105",
      title: "Used Rug - Persian 5x7",
      category: "Miscellaneous",
      price: 15000,
      location: "Westlands",
      condition: "Fair",
      featured: false,
      image: "assets/images/tv-unit-white-oak.jpg",
      description: "Persian style rug 5x7. Some wear.",
      seller: "Private Seller - Westlands"
    },
    {
      id: "sh-106",
      title: "Used Mirror - Full Length",
      category: "Miscellaneous",
      price: 3000,
      location: "Karen",
      condition: "Good",
      featured: false,
      image: "assets/images/sofa-grey-sectional-luxury.jpg",
      description: "Full length mirror. Wooden frame.",
      seller: "Private Seller - Karen"
    },
    {
      id: "sh-107",
      title: "Used Plant Stand - 3 Tier",
      category: "Miscellaneous",
      price: 2500,
      location: "Kisumu",
      condition: "Good",
      featured: false,
      image: "assets/images/sofa-gold-set-curtains.jpg",
      description: "3-tier plant stand. Metal.",
      seller: "Private Seller - Kisumu"
    },
    {
      id: "sh-108",
      title: "Used Coat Rack - Wooden",
      category: "Miscellaneous",
      price: 2000,
      location: "Mombasa",
      condition: "Good",
      featured: false,
      image: "assets/images/sofa-grey-u-shaped-teal.jpg",
      description: "Wooden coat rack. 6 hooks.",
      seller: "Private Seller - Mombasa"
    },
    {
      id: "sh-109",
      title: "Used Shoe Rack - 10 Pair",
      category: "Miscellaneous",
      price: 1500,
      location: "Nakuru",
      condition: "Good",
      featured: false,
      image: "assets/images/sofa-cream-sectional-set.jpg",
      description: "10-pair shoe rack. Metal.",
      seller: "Private Seller - Nakuru"
    },
    {
      id: "sh-110",
      title: "Used Magazine Rack - Wooden",
      category: "Miscellaneous",
      price: 1000,
      location: "Eldoret",
      condition: "Fair",
      featured: false,
      image: "assets/images/sofa-living-room-patterned.jpg",
      description: "Wooden magazine rack. Some scratches.",
      seller: "Private Seller - Eldoret"
    }
  ],

  // Categories for filtering
  categories: [
    "Used Sofas",
    "Used Office Furniture",
    "Used Electronics",
    "Used Tools",
    "Used Beds",
    "Used Appliances",
    "Used Building Materials",
    "Used Lighting",
    "Used Wardrobes",
    "Clearance Items",
    "Miscellaneous"
  ],

  // Conditions for filtering
  conditions: [
    "Like New",
    "Good",
    "Fair",
    "As-Is"
  ],

  // Locations for filtering
  locations: [
    "Nairobi",
    "Westlands",
    "Karen",
    "Kisumu",
    "Mombasa",
    "Nakuru",
    "Eldoret",
    "Kiambu"
  ],

  // Price ranges for filtering
  priceRanges: [
    { min: 0, max: 5000, label: "Under KSh 5,000" },
    { min: 5000, max: 20000, label: "KSh 5,000 - KSh 20,000" },
    { min: 20000, max: 50000, label: "KSh 20,000 - KSh 50,000" },
    { min: 50000, max: 999999, label: "KSh 50,000+" }
  ]
};
