/**
 * FURNOSTYLES — SOURCING/IMPORT DEMO DATA
 * =====================================
 * File: shared/demo-data/sourcing-demo.js
 * Purpose: Demo sourcing and import products for marketplace testing
 * 
 * This is TEST/DUMMY data for demonstration purposes only.
 * No real payments, no real users, no real transactions.
 */

window.FurnostylesSourcingDemo = {
  products: [
    // IMPORTED FURNITURE (10 items)
    {
      id: "src-001",
      title: "Italian Leather Sofa - Custom Order",
      category: "Imported Furniture",
      price: 285000,
      location: "Nairobi",
      origin: "Italy",
      leadTime: "8-12 weeks",
      featured: true,
      image: "assets/images/bed-burgundy-velvet-headboard.jpg",
      description: "Custom Italian leather sofa. Direct from manufacturer.",
      supplier: "East Africa Imports"
    },
    {
      id: "src-002",
      title: "German Office Chair - Ergonomic",
      category: "Imported Furniture",
      price: 65000,
      location: "Nairobi",
      origin: "Germany",
      leadTime: "4-6 weeks",
      featured: false,
      image: "assets/images/bed-brown-panel-headboard.jpg",
      description: "German ergonomic office chair. Premium quality.",
      supplier: "East Africa Imports"
    },
    {
      id: "src-003",
      title: "Swedish Dining Set - Oak 6 Seater",
      category: "Imported Furniture",
      price: 185000,
      location: "Mombasa",
      origin: "Sweden",
      leadTime: "6-8 weeks",
      featured: true,
      image: "assets/images/bed-grey-geometric-headboard.jpg",
      description: "Swedish oak dining set. Scandinavian design.",
      supplier: "Coastal Import Hub"
    },
    {
      id: "src-004",
      title: "Chinese Wardrobe - Modern 4 Door",
      category: "Imported Furniture",
      price: 95000,
      location: "Nairobi",
      origin: "China",
      leadTime: "4-6 weeks",
      featured: false,
      image: "assets/images/bed-grey-stripe-teal-bench.jpg",
      description: "Modern 4-door wardrobe. Direct factory order.",
      supplier: "East Africa Imports"
    },
    {
      id: "src-005",
      title: "Turkish Rug - Handmade 3x5m",
      category: "Imported Furniture",
      price: 145000,
      location: "Nairobi",
      origin: "Turkey",
      leadTime: "6-8 weeks",
      featured: false,
      image: "assets/images/tv-unit-white-gold-handles.jpg",
      description: "Handmade Turkish rug. Artisan craftsmanship.",
      supplier: "East Africa Imports"
    },
    {
      id: "src-006",
      title: "Spanish Bed Frame - King Size",
      category: "Imported Furniture",
      price: 125000,
      location: "Kisumu",
      origin: "Spain",
      leadTime: "6-8 weeks",
      featured: false,
      image: "assets/images/tv-unit-white-oak.jpg",
      description: "Spanish king bed frame. Ornate design.",
      supplier: "Lake Region Imports"
    },
    {
      id: "src-007",
      title: "Danish Coffee Table - Teak",
      category: "Imported Furniture",
      price: 65000,
      location: "Nairobi",
      origin: "Denmark",
      leadTime: "4-6 weeks",
      featured: false,
      image: "assets/images/sofa-grey-sectional-luxury.jpg",
      description: "Danish teak coffee table. Mid-century modern.",
      supplier: "East Africa Imports"
    },
    {
      id: "src-008",
      title: "Indian Console Table - Carved",
      category: "Imported Furniture",
      price: 55000,
      location: "Mombasa",
      origin: "India",
      leadTime: "4-6 weeks",
      featured: false,
      image: "assets/images/sofa-gold-set-curtains.jpg",
      description: "Carved Indian console table. Intricate details.",
      supplier: "Coastal Import Hub"
    },
    {
      id: "src-009",
      title: "French Armchair - Velvet",
      category: "Imported Furniture",
      price: 85000,
      location: "Nairobi",
      origin: "France",
      leadTime: "6-8 weeks",
      featured: true,
      image: "assets/images/sofa-grey-u-shaped-teal.jpg",
      description: "French velvet armchair. Louis XVI style.",
      supplier: "East Africa Imports"
    },
    {
      id: "src-010",
      title: "Japanese Platform Bed - Low Profile",
      category: "Imported Furniture",
      price: 75000,
      location: "Nakuru",
      origin: "Japan",
      leadTime: "6-8 weeks",
      featured: false,
      image: "assets/images/sofa-cream-sectional-set.jpg",
      description: "Japanese platform bed. Minimalist design.",
      supplier: "Rift Valley Imports"
    },

    // IMPORTED LIGHTING (8 items)
    {
      id: "src-011",
      title: "Italian Chandelier - Crystal 12 Light",
      category: "Imported Lighting",
      price: 185000,
      location: "Nairobi",
      origin: "Italy",
      leadTime: "4-6 weeks",
      featured: true,
      image: "assets/images/sofa-living-room-patterned.jpg",
      description: "Italian crystal chandelier. Luxury lighting.",
      supplier: "East Africa Imports"
    },
    {
      id: "src-012",
      title: "German LED Panel - 600x600",
      category: "Imported Lighting",
      price: 8500,
      location: "Westlands",
      origin: "Germany",
      leadTime: "2-4 weeks",
      featured: false,
      image: "assets/images/table-coffee-hardwood-1.jpg",
      description: "German LED panel. Office lighting.",
      supplier: "East Africa Imports"
    },
    {
      id: "src-013",
      title: "Chinese Pendant Lights - Set of 3",
      category: "Imported Lighting",
      price: 15000,
      location: "Nairobi",
      origin: "China",
      leadTime: "3-4 weeks",
      featured: false,
      image: "assets/images/table-coffee-hardwood-2.jpg",
      description: "Set of 3 pendant lights. Modern design.",
      supplier: "East Africa Imports"
    },
    {
      id: "src-014",
      title: "Spanish Wall Sconces - Brass Pair",
      category: "Imported Lighting",
      price: 12000,
      location: "Karen",
      origin: "Spain",
      leadTime: "4-6 weeks",
      featured: false,
      image: "assets/images/2.jpg",
      description: "Brass wall sconces. Traditional style.",
      supplier: "East Africa Imports"
    },
    {
      id: "src-015",
      title: "Dutch Floor Lamp - Adjustable",
      category: "Imported Lighting",
      price: 9500,
      location: "Mombasa",
      origin: "Netherlands",
      leadTime: "4-6 weeks",
      featured: false,
      image: "assets/images/bedroom-staging-modern-1.jpg",
      description: "Dutch adjustable floor lamp. Modern design.",
      supplier: "Coastal Import Hub"
    },
    {
      id: "src-016",
      title: "Japanese Paper Lanterns - Set of 5",
      category: "Imported Lighting",
      price: 8500,
      location: "Nairobi",
      origin: "Japan",
      leadTime: "3-4 weeks",
      featured: false,
      image: "assets/images/sofa-cream-bubble-wood-table.jpg",
      description: "Japanese paper lanterns. Ambient lighting.",
      supplier: "East Africa Imports"
    },
    {
      id: "src-017",
      title: "Turkish Mosaic Lamp - Table",
      category: "Imported Lighting",
      price: 6500,
      location: "Kisumu",
      origin: "Turkey",
      leadTime: "3-4 weeks",
      featured: false,
      image: "assets/images/sofa-brown-l-shaped-ottoman.jpg",
      description: "Turkish mosaic table lamp. Colorful.",
      supplier: "Lake Region Imports"
    },
    {
      id: "src-018",
      title: "French Outdoor Lights - Solar Set",
      category: "Imported Lighting",
      price: 18500,
      location: "Nairobi",
      origin: "France",
      leadTime: "4-6 weeks",
      featured: false,
      image: "assets/images/sofa-grey-l-shaped-teal.jpg",
      description: "French solar outdoor lights. Garden lighting.",
      supplier: "East Africa Imports"
    },

    // IMPORTED DECOR (8 items)
    {
      id: "src-019",
      title: "Moroccan Vases - Set of 3",
      category: "Imported Decor",
      price: 8500,
      location: "Nairobi",
      origin: "Morocco",
      leadTime: "3-4 weeks",
      featured: false,
      image: "assets/images/sofa-teal-velvet-set.jpg",
      description: "Moroccan ceramic vases. Hand-painted.",
      supplier: "East Africa Imports"
    },
    {
      id: "src-020",
      title: "Indian Cushions - Silk Set of 6",
      category: "Imported Decor",
      price: 6500,
      location: "Westlands",
      origin: "India",
      leadTime: "2-3 weeks",
      featured: false,
      image: "assets/images/living-room-modern-orange.jpg",
      description: "Indian silk cushions. Embroidered.",
      supplier: "East Africa Imports"
    },
    {
      id: "src-021",
      title: "Thai Wall Art - Wooden Carving",
      category: "Imported Decor",
      price: 12500,
      location: "Karen",
      origin: "Thailand",
      leadTime: "3-4 weeks",
      featured: false,
      image: "assets/images/living-room-beige-cozy.jpg",
      description: "Thai wooden wall carving. Intricate design.",
      supplier: "East Africa Imports"
    },
    {
      id: "src-022",
      title: "Egyptian Throw Blanket - Cotton",
      category: "Imported Decor",
      price: 4500,
      location: "Mombasa",
      origin: "Egypt",
      leadTime: "2-3 weeks",
      featured: false,
      image: "assets/images/property-kitchen-dining.jpg",
      description: "Egyptian cotton throw. Soft and warm.",
      supplier: "Coastal Import Hub"
    },
    {
      id: "src-023",
      title: "Indonesian Bamboo Basket Set",
      category: "Imported Decor",
      price: 3500,
      location: "Nairobi",
      origin: "Indonesia",
      leadTime: "3-4 weeks",
      featured: false,
      image: "assets/images/property-living-furnished.jpg",
      description: "Indonesian bamboo baskets. Storage solution.",
      supplier: "East Africa Imports"
    },
    {
      id: "src-024",
      title: "Mexican Pottery - Planters Set",
      category: "Imported Decor",
      price: 5500,
      location: "Kisumu",
      origin: "Mexico",
      leadTime: "4-6 weeks",
      featured: false,
      image: "assets/images/table-nesting-black-glass-1.jpg",
      description: "Mexican pottery planters. Colorful.",
      supplier: "Lake Region Imports"
    },
    {
      id: "src-025",
      title: "Persian Carpet - 2x3m",
      category: "Imported Decor",
      price: 65000,
      location: "Nairobi",
      origin: "Iran",
      leadTime: "6-8 weeks",
      featured: true,
      image: "assets/images/table-nesting-black-glass-2.jpg",
      description: "Persian carpet 2x3m. Hand-knotted.",
      supplier: "East Africa Imports"
    },
    {
      id: "src-026",
      title: "Ghanaian Textiles - Kente Cloth",
      category: "Imported Decor",
      price: 8500,
      location: "Nakuru",
      origin: "Ghana",
      leadTime: "2-3 weeks",
      featured: false,
      image: "assets/images/sofa-cream-set-marble.jpg",
      description: "Ghanaian Kente cloth. Traditional fabric.",
      supplier: "Rift Valley Imports"
    },

    // IMPORTED MACHINES (8 items)
    {
      id: "src-027",
      title: "German CNC Machine - Woodworking",
      category: "Imported Machines",
      price: 2850000,
      location: "Nairobi",
      origin: "Germany",
      leadTime: "12-16 weeks",
      featured: true,
      image: "assets/images/property-luxury-villa.jpg",
      description: "German CNC woodworking machine. Industrial grade.",
      supplier: "Industrial Imports Kenya"
    },
    {
      id: "src-028",
      title: "Japanese Excavator - 20 Ton",
      category: "Imported Machines",
      price: 8500000,
      location: "Mombasa",
      origin: "Japan",
      leadTime: "8-12 weeks",
      featured: true,
      image: "assets/images/bed-dark-wood-ottomans.jpg",
      description: "Japanese 20-ton excavator. Construction equipment.",
      supplier: "Coastal Import Hub"
    },
    {
      id: "src-029",
      title: "Italian Stone Cutter - Bridge Saw",
      category: "Imported Machines",
      price: 1450000,
      location: "Nairobi",
      origin: "Italy",
      leadTime: "8-10 weeks",
      featured: false,
      image: "assets/images/bedroom-staging-modern-2.jpg",
      description: "Italian bridge saw. Stone cutting.",
      supplier: "Industrial Imports Kenya"
    },
    {
      id: "src-030",
      title: "Chinese Tile Making Machine",
      category: "Imported Machines",
      price: 650000,
      location: "Nakuru",
      origin: "China",
      leadTime: "6-8 weeks",
      featured: false,
      image: "assets/images/bed-dark-headboard-blue.jpg",
      description: "Chinese tile making machine. Production line.",
      supplier: "Rift Valley Imports"
    },
    {
      id: "src-031",
      title: "American Forklift - 5 Ton",
      category: "Imported Machines",
      price: 850000,
      location: "Nairobi",
      origin: "USA",
      leadTime: "8-10 weeks",
      featured: false,
      image: "assets/images/bathroom-grey-modern.jpg",
      description: "American 5-ton forklift. Warehouse equipment.",
      supplier: "Industrial Imports Kenya"
    },
    {
      id: "src-032",
      title: "Korean Printing Press - Commercial",
      category: "Imported Machines",
      price: 1250000,
      location: "Westlands",
      origin: "South Korea",
      leadTime: "10-12 weeks",
      featured: false,
      image: "assets/images/table-coffee-round-wood.jpg",
      description: "Korean commercial printing press. Print shop.",
      supplier: "Industrial Imports Kenya"
    },
    {
      id: "src-033",
      title: "Swiss CNC Lathe - Precision",
      category: "Imported Machines",
      price: 3500000,
      location: "Nairobi",
      origin: "Switzerland",
      leadTime: "12-16 weeks",
      featured: true,
      image: "assets/images/bed-dark-wood-suite-1.jpg",
      description: "Swiss precision CNC lathe. Metalworking.",
      supplier: "Industrial Imports Kenya"
    },
    {
      id: "src-034",
      title: "Taiwan Injection Molding Machine",
      category: "Imported Machines",
      price: 950000,
      location: "Eldoret",
      origin: "Taiwan",
      leadTime: "8-10 weeks",
      featured: false,
      image: "assets/images/bed-burgundy-velvet-headboard.jpg",
      description: "Taiwan injection molding machine. Manufacturing.",
      supplier: "Highland Imports"
    },

    // IMPORTED FITTINGS (8 items)
    {
      id: "src-035",
      title: "German Kitchen Faucets - Premium Set",
      category: "Imported Fittings",
      price: 35000,
      location: "Nairobi",
      origin: "Germany",
      leadTime: "4-6 weeks",
      featured: true,
      image: "assets/images/bed-brown-panel-headboard.jpg",
      description: "German kitchen faucet set. Premium quality.",
      supplier: "East Africa Imports"
    },
    {
      id: "src-036",
      title: "Italian Bathroom Fixtures - Complete",
      category: "Imported Fittings",
      price: 85000,
      location: "Karen",
      origin: "Italy",
      leadTime: "6-8 weeks",
      featured: false,
      image: "assets/images/bed-grey-geometric-headboard.jpg",
      description: "Italian bathroom fixtures. Luxury suite.",
      supplier: "East Africa Imports"
    },
    {
      id: "src-037",
      title: "Japanese Electrical Switches - Smart",
      category: "Imported Fittings",
      price: 15000,
      location: "Westlands",
      origin: "Japan",
      leadTime: "3-4 weeks",
      featured: false,
      image: "assets/images/bed-grey-stripe-teal-bench.jpg",
      description: "Japanese smart switches. Home automation.",
      supplier: "East Africa Imports"
    },
    {
      id: "src-038",
      title: "Swiss Door Handles - Brass Set",
      category: "Imported Fittings",
      price: 12500,
      location: "Nairobi",
      origin: "Switzerland",
      leadTime: "4-6 weeks",
      featured: false,
      image: "assets/images/tv-unit-white-gold-handles.jpg",
      description: "Swiss brass door handles. Premium finish.",
      supplier: "East Africa Imports"
    },
    {
      id: "src-039",
      title: "French Window Hardware - Set",
      category: "Imported Fittings",
      price: 9500,
      location: "Mombasa",
      origin: "France",
      leadTime: "4-6 weeks",
      featured: false,
      image: "assets/images/tv-unit-white-oak.jpg",
      description: "French window hardware. Elegant design.",
      supplier: "Coastal Import Hub"
    },
    {
      id: "src-040",
      title: "Spanish Plumbing Fixtures - Luxury",
      category: "Imported Fittings",
      price: 45000,
      location: "Kisumu",
      origin: "Spain",
      leadTime: "6-8 weeks",
      featured: false,
      image: "assets/images/sofa-grey-sectional-luxury.jpg",
      description: "Spanish luxury plumbing fixtures. Designer.",
      supplier: "Lake Region Imports"
    },
    {
      id: "src-041",
      title: "British Locks - Smart Lock Set",
      category: "Imported Fittings",
      price: 25000,
      location: "Nairobi",
      origin: "UK",
      leadTime: "4-6 weeks",
      featured: false,
      image: "assets/images/sofa-gold-set-curtains.jpg",
      description: "British smart lock set. Keyless entry.",
      supplier: "East Africa Imports"
    },
    {
      id: "src-042",
      title: "Dutch Hinges - Heavy Duty",
      category: "Imported Fittings",
      price: 6500,
      location: "Nakuru",
      origin: "Netherlands",
      leadTime: "3-4 weeks",
      featured: false,
      image: "assets/images/sofa-grey-u-shaped-teal.jpg",
      description: "Dutch heavy-duty hinges. Industrial grade.",
      supplier: "Rift Valley Imports"
    },

    // BULK MATERIALS (8 items)
    {
      id: "src-043",
      title: "Bulk Cement - 50 Tons",
      category: "Bulk Materials",
      price: 375000,
      location: "Nairobi",
      origin: "Kenya",
      leadTime: "1-2 weeks",
      featured: true,
      image: "assets/images/sofa-cream-sectional-set.jpg",
      description: "50 tons of cement. Wholesale pricing.",
      supplier: "Builders Depot Kenya"
    },
    {
      id: "src-044",
      title: "Bulk Steel Bars - 20 Tons",
      category: "Bulk Materials",
      price: 1700000,
      location: "Mombasa",
      origin: "Kenya",
      leadTime: "2-3 weeks",
      featured: true,
      image: "assets/images/sofa-living-room-patterned.jpg",
      description: "20 tons of steel bars. Construction grade.",
      supplier: "Coastal Building Supplies"
    },
    {
      id: "src-045",
      title: "Bulk Sand - 100 Truckloads",
      category: "Bulk Materials",
      price: 250000,
      location: "Nairobi",
      origin: "Kenya",
      leadTime: "2-4 weeks",
      featured: false,
      image: "assets/images/table-coffee-hardwood-1.jpg",
      description: "100 truckloads of river sand. Large project.",
      supplier: "Builders Depot Kenya"
    },
    {
      id: "src-046",
      title: "Bulk Ballast - 80 Truckloads",
      category: "Bulk Materials",
      price: 280000,
      location: "Nakuru",
      origin: "Kenya",
      leadTime: "2-4 weeks",
      featured: false,
      image: "assets/images/table-coffee-hardwood-2.jpg",
      description: "80 truckloads of ballast. Aggregate supply.",
      supplier: "Rift Valley Hardware"
    },
    {
      id: "src-047",
      title: "Bulk Timber - Pine 5000 pcs",
      category: "Bulk Materials",
      price: 2250000,
      location: "Nairobi",
      origin: "Kenya",
      leadTime: "3-4 weeks",
      featured: false,
      image: "assets/images/2.jpg",
      description: "5000 pieces of pine timber. Wholesale.",
      supplier: "Timber Yard Kenya"
    },
    {
      id: "src-048",
      title: "Bulk Gypsum Boards - 1000 sheets",
      category: "Bulk Materials",
      price: 1250000,
      location: "Kisumu",
      origin: "Kenya",
      leadTime: "2-3 weeks",
      featured: false,
      image: "assets/images/bedroom-staging-modern-1.jpg",
      description: "1000 gypsum boards. Large project supply.",
      supplier: "Lake Region Hardware"
    },
    {
      id: "src-049",
      title: "Bulk Roofing Sheets - 5000 pcs",
      category: "Bulk Materials",
      price: 9250000,
      location: "Eldoret",
      origin: "Kenya",
      leadTime: "3-4 weeks",
      featured: false,
      image: "assets/images/sofa-cream-bubble-wood-table.jpg",
      description: "5000 roofing sheets. Wholesale pricing.",
      supplier: "Highland Building Materials"
    },
    {
      id: "src-050",
      title: "Bulk Tiles - Ceramic 10000 pcs",
      category: "Bulk Materials",
      price: 12000000,
      location: "Nairobi",
      origin: "Kenya",
      leadTime: "4-6 weeks",
      featured: true,
      image: "assets/images/sofa-brown-l-shaped-ottoman.jpg",
      description: "10000 ceramic tiles. Large development.",
      supplier: "Tile Masters Kenya"
    },

    // SUPPLIER PRODUCTS (10 items)
    {
      id: "src-051",
      title: "Alibaba Sourced - LED Lights Bulk",
      category: "Supplier Products",
      price: 450000,
      location: "Nairobi",
      origin: "China",
      leadTime: "4-6 weeks",
      featured: false,
      image: "assets/images/sofa-grey-l-shaped-teal.jpg",
      description: "500 LED lights from Alibaba. Bulk order.",
      supplier: "East Africa Imports"
    },
    {
      id: "src-052",
      title: "Alibaba Sourced - Kitchen Faucets",
      category: "Supplier Products",
      price: 285000,
      location: "Nairobi",
      origin: "China",
      leadTime: "4-6 weeks",
      featured: false,
      image: "assets/images/sofa-teal-velvet-set.jpg",
      description: "300 kitchen faucets from Alibaba. Wholesale.",
      supplier: "East Africa Imports"
    },
    {
      id: "src-053",
      title: "Alibaba Sourced - Door Handles",
      category: "Supplier Products",
      price: 185000,
      location: "Westlands",
      origin: "China",
      leadTime: "3-4 weeks",
      featured: false,
      image: "assets/images/living-room-modern-orange.jpg",
      description: "1000 door handles from Alibaba. Bulk.",
      supplier: "East Africa Imports"
    },
    {
      id: "src-054",
      title: "Made-in-China - Power Tools Set",
      category: "Supplier Products",
      price: 650000,
      location: "Nairobi",
      origin: "China",
      leadTime: "4-6 weeks",
      featured: false,
      image: "assets/images/living-room-beige-cozy.jpg",
      description: "200 power tools from Made-in-China. Wholesale.",
      supplier: "Industrial Imports Kenya"
    },
    {
      id: "src-055",
      title: "Global Sources - Solar Panels",
      category: "Supplier Products",
      price: 2850000,
      location: "Mombasa",
      origin: "China",
      leadTime: "6-8 weeks",
      featured: true,
      image: "assets/images/property-kitchen-dining.jpg",
      description: "100 solar panels from Global Sources. Energy.",
      supplier: "Coastal Import Hub"
    },
    {
      id: "src-056",
      title: "DHgate - Home Decor Bulk",
      category: "Supplier Products",
      price: 385000,
      location: "Nairobi",
      origin: "China",
      leadTime: "3-4 weeks",
      featured: false,
      image: "assets/images/property-living-furnished.jpg",
      description: "500 home decor items from DHgate. Wholesale.",
      supplier: "East Africa Imports"
    },
    {
      id: "src-057",
      title: "1688 - Building Materials Mix",
      category: "Supplier Products",
      price: 1450000,
      location: "Nakuru",
      origin: "China",
      leadTime: "4-6 weeks",
      featured: false,
      image: "assets/images/table-nesting-black-glass-1.jpg",
      description: "Mixed building materials from 1688. Bulk.",
      supplier: "Rift Valley Imports"
    },
    {
      id: "src-058",
      title: "Taobao - Kitchen Gadgets Set",
      category: "Supplier Products",
      price: 285000,
      location: "Kisumu",
      origin: "China",
      leadTime: "2-3 weeks",
      featured: false,
      image: "assets/images/table-nesting-black-glass-2.jpg",
      description: "1000 kitchen gadgets from Taobao. Wholesale.",
      supplier: "Lake Region Imports"
    },
    {
      id: "src-059",
      title: "AliExpress - Smart Home Devices",
      category: "Supplier Products",
      price: 485000,
      location: "Nairobi",
      origin: "China",
      leadTime: "3-4 weeks",
      featured: false,
      image: "assets/images/sofa-cream-set-marble.jpg",
      description: "200 smart home devices from AliExpress. Tech.",
      supplier: "East Africa Imports"
    },
    {
      id: "src-060",
      title: "Banggood - Garden Tools Set",
      category: "Supplier Products",
      price: 385000,
      location: "Eldoret",
      origin: "China",
      leadTime: "3-4 weeks",
      featured: false,
      image: "assets/images/property-luxury-villa.jpg",
      description: "300 garden tools from Banggood. Outdoor.",
      supplier: "Highland Imports"
    }
  ],

  // Categories for filtering
  categories: [
    "Imported Furniture",
    "Imported Lighting",
    "Imported Decor",
    "Imported Machines",
    "Imported Fittings",
    "Bulk Materials",
    "Supplier Products"
  ],

  // Origins for filtering
  origins: [
    "Italy",
    "Germany",
    "China",
    "Spain",
    "France",
    "Japan",
    "Turkey",
    "India",
    "Kenya",
    "USA",
    "UK",
    "Switzerland",
    "Sweden",
    "Denmark",
    "Netherlands",
    "Morocco",
    "Thailand",
    "Egypt",
    "Indonesia",
    "Mexico",
    "Iran",
    "Ghana",
    "South Korea",
    "Taiwan"
  ],

  // Locations for filtering
  locations: [
    "Nairobi",
    "Westlands",
    "Karen",
    "Kisumu",
    "Mombasa",
    "Nakuru",
    "Eldoret"
  ],

  // Lead times for filtering
  leadTimes: [
    "1-2 weeks",
    "2-3 weeks",
    "3-4 weeks",
    "4-6 weeks",
    "6-8 weeks",
    "8-12 weeks",
    "12-16 weeks"
  ]
};
